-- =====================================================================
-- License Exam Prep — database schema (public)
--
-- Reconstructed on 2026-09-25 for the new project `dev_license_app` (which
-- later becomes production) from the old project's API description (tables,
-- columns, defaults, keys) and from what the app code reads and writes.
-- The old project was deliberately not touched.
--
-- Apply with:  node tools/dev_db.mjs schema   (direct Postgres, dev only)
-- or paste into the project's SQL Editor. Idempotent: safe to re-run.
--
-- Order: content tables → user tables → indexes → RLS + policies →
--        functions (RPC) → triggers → grants.
--
-- Checked against the live dev_license_app database on 2026-09-26: tables,
-- columns, keys, indexes, policies, functions and triggers all match.
-- =====================================================================

create extension if not exists "uuid-ossp";
create extension if not exists pgcrypto;   -- gen_random_uuid()

-- ---------------------------------------------------------------------
-- Content (public, read-only for the app; written by the import tools)
-- ---------------------------------------------------------------------
create table if not exists public.chapters (
  id          text primary key,
  title       text not null,
  description text not null,
  emoji       text not null,
  icon        text,
  "order"     integer not null
);

create table if not exists public.topics (
  id              text primary key,
  chapter_id      text not null references public.chapters(id),
  title           text not null,
  description     text not null,
  icon            text,
  "order"         integer not null,
  -- Chapter 1 restructure: NULL = top-level topic; otherwise the group it belongs to.
  parent_topic_id text references public.topics(id)
);
create index if not exists topics_parent_topic_id_idx on public.topics(parent_topic_id);
create index if not exists topics_chapter_id_idx on public.topics(chapter_id);

create table if not exists public.theory_content (
  topic_id text primary key references public.topics(id),
  concepts jsonb not null default '[]'::jsonb,
  formulas jsonb not null default '[]'::jsonb,
  notes    jsonb not null default '[]'::jsonb
);

create table if not exists public.questions (
  id            text primary key,
  chapter_id    text not null references public.chapters(id),
  topic_id      text not null references public.topics(id),
  question_text text not null,
  correct_index integer not null,
  explanation   text not null default '',
  difficulty    text not null default 'medium',
  formula       text,
  code_snippet  text,
  code_language text
);
create index if not exists questions_chapter_id_idx on public.questions(chapter_id);
create index if not exists questions_topic_id_idx on public.questions(topic_id);

create table if not exists public.question_options (
  id           bigint generated by default as identity primary key,
  question_id  text not null references public.questions(id) on delete cascade,
  option_index integer not null,
  option_text  text not null,
  unique (question_id, option_index)
);

create table if not exists public.formulas (
  id          text primary key,
  chapter_id  text not null references public.chapters(id),
  topic_id    text not null references public.topics(id),
  title       text not null,
  description text not null default '',
  latex       text,
  plain_text  text not null,
  is_code     boolean default false
);
create index if not exists formulas_chapter_id_idx on public.formulas(chapter_id);

create table if not exists public.flashcards (
  id         text primary key,
  chapter_id text not null references public.chapters(id),
  topic_id   text not null references public.topics(id),
  front      text not null,
  back       text not null,
  difficulty text not null default 'medium'
);
create index if not exists flashcards_chapter_id_idx on public.flashcards(chapter_id);

-- ---------------------------------------------------------------------
-- Per-user data (row-level security: users see and change only their own rows)
-- ---------------------------------------------------------------------
create table if not exists public.profiles (
  id                    uuid primary key references auth.users(id) on delete cascade,
  theme_mode            text default 'system',
  preferred_quiz_length integer default 10,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

create table if not exists public.user_topic_progress (
  user_id         uuid not null references auth.users(id) on delete cascade,
  topic_id        text not null references public.topics(id),
  completed       boolean not null default false,
  completion_pct  double precision not null default 0,
  last_studied_at timestamptz not null default now(),
  primary key (user_id, topic_id)
);

create table if not exists public.bookmarks (
  user_id    uuid not null references auth.users(id) on delete cascade,
  item_type  text not null,            -- 'question' | 'formula' | 'topic'
  item_id    text not null,
  created_at timestamptz not null default now(),
  primary key (user_id, item_type, item_id)
);

create table if not exists public.flashcard_reviews (
  user_id          uuid not null references auth.users(id) on delete cascade,
  card_id          text not null references public.flashcards(id) on delete cascade,
  ease             double precision not null default 2.5,
  interval_days    integer not null default 1,
  due_date         timestamptz not null default now(),
  review_count     integer not null default 0,
  last_reviewed_at timestamptz not null default now(),
  primary key (user_id, card_id)
);

create table if not exists public.quiz_results (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null references auth.users(id) on delete cascade,
  mode           text not null,        -- practice | timed | mock | bookmarked | fullExam
  chapter_id     text references public.chapters(id),
  score_achieved integer not null,
  score_total    integer not null,
  percentage     double precision not null,
  time_seconds   integer not null,
  taken_at       timestamptz not null default now()
);
create index if not exists quiz_results_user_id_idx on public.quiz_results(user_id, taken_at desc);

create table if not exists public.question_attempts (
  id             uuid primary key default gen_random_uuid(),
  result_id      uuid not null references public.quiz_results(id) on delete cascade,
  user_id        uuid not null references auth.users(id) on delete cascade,
  question_id    text not null references public.questions(id),
  chapter_id     text references public.chapters(id),
  topic_id       text references public.topics(id),
  selected_index integer not null,
  is_correct     boolean not null,
  time_ms        integer not null
);
create index if not exists question_attempts_user_id_idx on public.question_attempts(user_id);

create table if not exists public.study_activity (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references auth.users(id) on delete cascade,
  activity_date date not null,
  source        text not null default 'app',
  created_at    timestamptz not null default now(),
  -- the app upserts on (user_id, activity_date)
  unique (user_id, activity_date)
);

-- Latest Practice-mode answer per user per question (see
-- migrations/20260927_question_progress.sql). No FK to questions on purpose.
create table if not exists public.question_progress (
  user_id     uuid not null references auth.users(id) on delete cascade,
  question_id text not null,
  is_correct  boolean not null,
  answered_at timestamptz not null default now(),
  primary key (user_id, question_id)
);

-- ---------------------------------------------------------------------
-- Row-level security
-- ---------------------------------------------------------------------
alter table public.chapters             enable row level security;
alter table public.topics               enable row level security;
alter table public.theory_content       enable row level security;
alter table public.questions            enable row level security;
alter table public.question_options     enable row level security;
alter table public.formulas             enable row level security;
alter table public.flashcards           enable row level security;
alter table public.profiles             enable row level security;
alter table public.user_topic_progress  enable row level security;
alter table public.bookmarks            enable row level security;
alter table public.flashcard_reviews    enable row level security;
alter table public.quiz_results         enable row level security;
alter table public.question_attempts    enable row level security;
alter table public.study_activity       enable row level security;
alter table public.question_progress    enable row level security;

-- Content: anyone (signed in or not) may read; only the service role writes.
do $$
declare t text;
begin
  foreach t in array array['chapters','topics','theory_content','questions','question_options','formulas','flashcards'] loop
    execute format('drop policy if exists "content is public" on public.%I', t);
    execute format('create policy "content is public" on public.%I for select to anon, authenticated using (true)', t);
  end loop;
end $$;

-- Per-user tables: full access to your own rows only.
do $$
declare t text;
begin
  foreach t in array array['user_topic_progress','bookmarks','flashcard_reviews','quiz_results','question_attempts','study_activity','question_progress'] loop
    execute format('drop policy if exists "own rows" on public.%I', t);
    execute format('create policy "own rows" on public.%I for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id)', t);
  end loop;
end $$;

drop policy if exists "own profile" on public.profiles;
create policy "own profile" on public.profiles
  for all to authenticated using (auth.uid() = id) with check (auth.uid() = id);

-- ---------------------------------------------------------------------
-- Functions (RPC)
-- ---------------------------------------------------------------------

-- Saves a finished quiz and its per-question attempts in one transaction and
-- logs the day's study activity for the streak. Called by the app as
--   rpc('save_quiz_result', {p_mode, p_chapter_id, p_score_achieved,
--       p_score_total, p_percentage, p_time_seconds, p_attempts: [...]})
-- p_attempts items: {question_id, chapter_id, topic_id, selected_index, is_correct, time_ms}
create or replace function public.save_quiz_result(
  p_mode           text,
  p_chapter_id     text,
  p_score_achieved integer,
  p_score_total    integer,
  p_percentage     double precision,
  p_time_seconds   integer,
  p_attempts       jsonb
) returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user   uuid := auth.uid();
  v_result uuid;
begin
  if v_user is null then
    raise exception 'not signed in' using errcode = '42501';
  end if;

  insert into public.quiz_results (user_id, mode, chapter_id, score_achieved, score_total, percentage, time_seconds)
  values (v_user, p_mode, nullif(p_chapter_id, ''), p_score_achieved, p_score_total, p_percentage, p_time_seconds)
  returning id into v_result;

  insert into public.question_attempts (result_id, user_id, question_id, chapter_id, topic_id, selected_index, is_correct, time_ms)
  select v_result, v_user,
         a->>'question_id',
         nullif(a->>'chapter_id', ''),
         nullif(a->>'topic_id', ''),
         coalesce((a->>'selected_index')::integer, -1),
         coalesce((a->>'is_correct')::boolean, false),
         coalesce((a->>'time_ms')::integer, 0)
  from jsonb_array_elements(coalesce(p_attempts, '[]'::jsonb)) as a
  where a ? 'question_id';

  insert into public.study_activity (user_id, activity_date, source)
  values (v_user, current_date, 'quiz')
  on conflict (user_id, activity_date) do nothing;

  return v_result;
end;
$$;
revoke all on function public.save_quiz_result(text, text, integer, integer, double precision, integer, jsonb) from public;
grant execute on function public.save_quiz_result(text, text, integer, integer, double precision, integer, jsonb) to authenticated, service_role;

-- Maintenance helper: turns RLS on for every table in public (no-op when already on).
create or replace function public.rls_auto_enable()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare t text;
begin
  for t in select tablename from pg_tables where schemaname = 'public' loop
    execute format('alter table public.%I enable row level security', t);
  end loop;
end;
$$;
revoke all on function public.rls_auto_enable() from public;
grant execute on function public.rls_auto_enable() to service_role;

-- ---------------------------------------------------------------------
-- Triggers
-- ---------------------------------------------------------------------

-- A profile row per auth user (full_name / phone stay in auth.users metadata).
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id) values (new.id) on conflict (id) do nothing;
  return new;
end;
$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;
drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at
  before update on public.profiles
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------
-- Grants (Supabase's API roles)
-- ---------------------------------------------------------------------
grant usage on schema public to anon, authenticated, service_role;
grant select on all tables in schema public to anon, authenticated;
grant all on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to authenticated, service_role;
grant insert, update, delete on public.profiles, public.user_topic_progress, public.bookmarks,
  public.flashcard_reviews, public.quiz_results, public.question_attempts, public.study_activity,
  public.question_progress
  to authenticated;
