// tools/gen_chapter_migration.mjs — emits the topic → subtopic migration for one chapter
// from supabase/content/<chapter>/tree.json, in the same shape as the hand-written
// Chapter 1 migration (backups, tmp_ routing for colliding ids, theory concatenation,
// progress merge, drops), so every chapter is restructured the same proven way.
//
//   node tools/gen_chapter_migration.mjs ch2 > supabase/migrations/<date>_ch2_topic_hierarchy.sql
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const chapter = process.argv[2];
if (!/^ch\d+$/.test(chapter || '')) { console.error('usage: node tools/gen_chapter_migration.mjs chN'); process.exit(1); }
const tree = JSON.parse(fs.readFileSync(path.join(root, 'supabase', 'content', chapter, 'tree.json'), 'utf8'));
if (tree.chapter !== chapter) throw new Error(`tree.json is for ${tree.chapter}`);

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const stamp = new Date().toISOString().slice(0, 10).replace(/-/g, '');
const like = `${chapter}\\_%`;
const drop = tree.drop || [];
const skipTheory = new Set(tree.skipTheoryFrom || []);

const newTopics = [];
tree.parents.forEach((p, pi) => {
  newTopics.push([p.id, null, p.title, pi + 1]);
  p.subtopics.forEach((s, si) => newTopics.push([s.id, p.id, s.title, si + 1]));
});
const newIds = new Set(newTopics.map((t) => t[0]));
for (const [oldId, m] of Object.entries(tree.map)) {
  if (!newIds.has(m.to)) throw new Error(`map: ${oldId} → ${m.to} is not in the tree`);
}

const sql = `-- =====================================================================
-- ${chapter.toUpperCase()} restructure: Chapter -> Topic (parent) -> Subtopic
-- Generated by tools/gen_chapter_migration.mjs from supabase/content/${chapter}/tree.json
-- on ${stamp}. Same mechanics as the Chapter 1 migration:
--   * parent topics ${tree.parents.map((p) => p.id).join(', ')}
--   * every existing ${chapter} topic re-pointed via tmp_ ids (old/new ids overlap)
--   * questions, flashcards, formulas, theory, progress and attempts follow
--   * dropped topics: ${drop.length ? drop.join(', ') : 'none'}
-- Runs as one transaction; backups go to schema "backup".
-- =====================================================================

begin;
${tree.chapterRow ? `
-- New chapter row (a chapter with no earlier app content).
insert into public.chapters (id, title, description, emoji, icon, "order")
values (${q(chapter)}, ${q(tree.chapterRow.title)}, ${q(tree.chapterRow.description)}, ${q(tree.chapterRow.emoji)}, ${tree.chapterRow.icon ? q(tree.chapterRow.icon) : 'null'}, ${Number(tree.chapterRow.order)})
on conflict (id) do update set title = excluded.title, description = excluded.description,
  emoji = excluded.emoji, icon = excluded.icon, "order" = excluded."order";
` : ''}
create schema if not exists backup;
create table backup.${chapter}_topics_${stamp}         as select * from public.topics              where chapter_id = ${q(chapter)};
create table backup.${chapter}_theory_content_${stamp} as select * from public.theory_content      where topic_id like ${q(like)};
create table backup.${chapter}_questions_${stamp}      as select * from public.questions           where chapter_id = ${q(chapter)};
create table backup.${chapter}_question_options_${stamp} as select o.* from public.question_options o join public.questions q on q.id = o.question_id where q.chapter_id = ${q(chapter)};
create table backup.${chapter}_flashcards_${stamp}     as select * from public.flashcards          where chapter_id = ${q(chapter)};
create table backup.${chapter}_flashcard_reviews_${stamp} as select r.* from public.flashcard_reviews r join public.flashcards f on f.id = r.card_id where f.chapter_id = ${q(chapter)};
create table backup.${chapter}_formulas_${stamp}       as select * from public.formulas            where chapter_id = ${q(chapter)};
create table backup.${chapter}_progress_${stamp}       as select * from public.user_topic_progress where topic_id like ${q(like)};
create table backup.${chapter}_attempts_${stamp}       as select * from public.question_attempts   where chapter_id = ${q(chapter)};

alter table public.topics add column if not exists parent_topic_id text references public.topics(id);
create index if not exists topics_parent_topic_id_idx on public.topics(parent_topic_id);

-- Dropped topics and everything attached to them.
create temp table drop_topics(id text primary key) on commit drop;
${drop.length ? `insert into drop_topics values ${drop.map((d) => `(${q(d)})`).join(', ')};` : '-- (none)'}
delete from public.question_attempts where topic_id in (select id from drop_topics)
   or question_id in (select id from public.questions where topic_id in (select id from drop_topics));
delete from public.question_options  where question_id in (select id from public.questions where topic_id in (select id from drop_topics));
delete from public.questions         where topic_id in (select id from drop_topics);
delete from public.flashcard_reviews where card_id in (select id from public.flashcards where topic_id in (select id from drop_topics));
delete from public.flashcards        where topic_id in (select id from drop_topics);
delete from public.formulas          where topic_id in (select id from drop_topics);
delete from public.theory_content    where topic_id in (select id from drop_topics);
delete from public.user_topic_progress where topic_id in (select id from drop_topics);

-- Final tree.
create temp table new_topics(id text primary key, parent text, title text, ord int) on commit drop;
insert into new_topics values
${newTopics.map(([id, parent, title, ord]) => `  (${q(id)}, ${parent ? q(parent) : 'null'}, ${q(title)}, ${ord})`).join(',\n')};

-- Old id -> new id; seq orders theory blocks when old topics merge.
create temp table id_map(old_id text primary key, new_id text, seq int) on commit drop;
${Object.keys(tree.map).length ? `insert into id_map values
${Object.entries(tree.map).map(([o, m]) => `  (${q(o)}, ${q(m.to)}, ${m.seq || 1})`).join(',\n')};` : '-- (no existing topics to map)'}

do $$
declare missing text;
begin
  select string_agg(id, ', ') into missing
  from public.topics
  where chapter_id = ${q(chapter)}
    and id not in (select old_id from id_map)
    and id not in (select id from drop_topics);
  if missing is not null then
    raise exception 'Unmapped ${chapter} topics: %', missing;
  end if;
end $$;

-- Stage through temporary topics.
insert into public.topics (id, chapter_id, title, description, icon, "order")
select distinct 'tmp_' || new_id, ${q(chapter)}, 'tmp', 'tmp', null, 0 from id_map;

update public.questions           x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;
update public.question_attempts   x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;
update public.flashcards          x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;
update public.formulas            x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;

create temp table progress_stage on commit drop as
select p.user_id, 'tmp_' || m.new_id as topic_id,
       bool_or(p.completed) as completed, max(p.completion_pct) as completion_pct, max(p.last_studied_at) as last_studied_at
from public.user_topic_progress p join id_map m on m.old_id = p.topic_id
group by p.user_id, m.new_id;
delete from public.user_topic_progress where topic_id in (select old_id from id_map);
insert into public.user_topic_progress (user_id, topic_id, completed, completion_pct, last_studied_at)
select user_id, topic_id, completed, completion_pct, last_studied_at from progress_stage;

create temp table theory_stage on commit drop as
select 'tmp_' || m.new_id as topic_id,
       coalesce(jsonb_agg(e.b order by m.seq, e.n) filter (where e.kind = 'concepts'), '[]'::jsonb) as concepts,
       coalesce(jsonb_agg(e.b order by m.seq, e.n) filter (where e.kind = 'formulas'), '[]'::jsonb) as formulas,
       coalesce(jsonb_agg(e.b order by m.seq, e.n) filter (where e.kind = 'notes'),    '[]'::jsonb) as notes
from public.theory_content t
join id_map m on m.old_id = t.topic_id${skipTheory.size ? ` and m.old_id not in (${[...skipTheory].map(q).join(', ')})` : ''}
cross join lateral (
  select 'concepts' as kind, x.b, x.n from jsonb_array_elements(coalesce(t.concepts, '[]')) with ordinality x(b, n)
  union all
  select 'formulas', x.b, x.n from jsonb_array_elements(coalesce(t.formulas, '[]')) with ordinality x(b, n)
  union all
  select 'notes',    x.b, x.n from jsonb_array_elements(coalesce(t.notes, '[]'))    with ordinality x(b, n)
) e
group by m.new_id;
delete from public.theory_content where topic_id in (select old_id from id_map);
insert into public.theory_content (topic_id, concepts, formulas, notes)
select topic_id, concepts, formulas, notes from theory_stage;

-- Replace the old ${chapter} topics with the tree (parents first for the FK).
delete from public.topics where chapter_id = ${q(chapter)} and id not like 'tmp\\_%';
insert into public.topics (id, chapter_id, title, description, icon, "order", parent_topic_id)
select id, ${q(chapter)}, title, title, null, ord, parent from new_topics where parent is null;
insert into public.topics (id, chapter_id, title, description, icon, "order", parent_topic_id)
select id, ${q(chapter)}, title, title, null, ord, parent from new_topics where parent is not null;

update public.questions           set topic_id = substr(topic_id, 5) where topic_id like ${q('tmp\\_' + like)};
update public.question_attempts   set topic_id = substr(topic_id, 5) where topic_id like ${q('tmp\\_' + like)};
update public.flashcards          set topic_id = substr(topic_id, 5) where topic_id like ${q('tmp\\_' + like)};
update public.formulas            set topic_id = substr(topic_id, 5) where topic_id like ${q('tmp\\_' + like)};
update public.user_topic_progress set topic_id = substr(topic_id, 5) where topic_id like ${q('tmp\\_' + like)};
update public.theory_content      set topic_id = substr(topic_id, 5) where topic_id like ${q('tmp\\_' + like)};
delete from public.topics where id like ${q('tmp\\_' + like)};

commit;

-- Verification (shown as the result)
select coalesce(p."order", t."order") as topic_no, coalesce(p.title, t.title) as topic, t.id, t.title as subtopic,
       (select count(*) from public.questions  q where q.topic_id = t.id) as questions,
       (select count(*) from public.flashcards f where f.topic_id = t.id) as flashcards,
       (select count(*) from public.formulas   f where f.topic_id = t.id) as formulas,
       (select coalesce(jsonb_array_length(c.concepts), 0) from public.theory_content c where c.topic_id = t.id) as concept_blocks
from public.topics t left join public.topics p on p.id = t.parent_topic_id
where t.chapter_id = ${q(chapter)}
order by coalesce(p."order", t."order"), t.parent_topic_id nulls first, t."order";
`;
process.stdout.write(sql);
