-- =====================================================================
-- CH8 restructure: Chapter -> Topic (parent) -> Subtopic
-- Generated by tools/gen_chapter_migration.mjs from supabase/content/ch8/tree.json
-- on 20260925. Same mechanics as the Chapter 1 migration:
--   * parent topics ch8_p1, ch8_p2, ch8_p3, ch8_p4, ch8_p5, ch8_p6, ch8_p7
--   * every existing ch8 topic re-pointed via tmp_ ids (old/new ids overlap)
--   * questions, flashcards, formulas, theory, progress and attempts follow
--   * dropped topics: none
-- Runs as one transaction; backups go to schema "backup".
-- =====================================================================

begin;

create schema if not exists backup;
create table backup.ch8_topics_20260925         as select * from public.topics              where chapter_id = 'ch8';
create table backup.ch8_theory_content_20260925 as select * from public.theory_content      where topic_id like 'ch8\_%';
create table backup.ch8_questions_20260925      as select * from public.questions           where chapter_id = 'ch8';
create table backup.ch8_question_options_20260925 as select o.* from public.question_options o join public.questions q on q.id = o.question_id where q.chapter_id = 'ch8';
create table backup.ch8_flashcards_20260925     as select * from public.flashcards          where chapter_id = 'ch8';
create table backup.ch8_flashcard_reviews_20260925 as select r.* from public.flashcard_reviews r join public.flashcards f on f.id = r.card_id where f.chapter_id = 'ch8';
create table backup.ch8_formulas_20260925       as select * from public.formulas            where chapter_id = 'ch8';
create table backup.ch8_progress_20260925       as select * from public.user_topic_progress where topic_id like 'ch8\_%';
create table backup.ch8_attempts_20260925       as select * from public.question_attempts   where chapter_id = 'ch8';

alter table public.topics add column if not exists parent_topic_id text references public.topics(id);
create index if not exists topics_parent_topic_id_idx on public.topics(parent_topic_id);

-- Dropped topics and everything attached to them.
create temp table drop_topics(id text primary key) on commit drop;
-- (none)
delete from public.question_attempts where topic_id in (select id from drop_topics)
   or question_id in (select id from public.questions where topic_id in (select id from drop_topics));
delete from public.question_options  where question_id in (select id from public.questions where topic_id in (select id from drop_topics));
delete from public.questions         where topic_id in (select id from drop_topics);
delete from public.flashcard_reviews where card_id in (select id from public.flashcards where topic_id in (select id from drop_topics));
delete from public.flashcards        where topic_id in (select id from drop_topics);
delete from public.formulas          where topic_id in (select id from drop_topics);
delete from public.theory_content    where topic_id in (select id from drop_topics);
delete from public.user_topic_progress where topic_id in (select id from drop_topics);

-- Final tree.
create temp table new_topics(id text primary key, parent text, title text, ord int) on commit drop;
insert into new_topics values
  ('ch8_p1', null, 'Software Process & Requirements', 1),
  ('ch8_t1', 'ch8_p1', 'Software Characteristics & Quality Attributes', 1),
  ('ch8_i11', 'ch8_p1', 'Software Process Models: Agile, V, Iterative, Prototype & Big Bang', 2),
  ('ch8_i12', 'ch8_p1', 'Computer-Aided Software Engineering (CASE)', 3),
  ('ch8_i13', 'ch8_p1', 'Functional, Non-Functional, User & System Requirements', 4),
  ('ch8_i14', 'ch8_p1', 'Requirements Engineering: Elicitation, Analysis, SRS, Validation & Management', 5),
  ('ch8_p2', null, 'Software Design', 2),
  ('ch8_t2', 'ch8_p2', 'Design Process, Concepts, Heuristics, Coupling & Cohesion', 1),
  ('ch8_i21', 'ch8_p2', 'Architectural Design: Decisions, Organization, Decomposition & Control Styles', 2),
  ('ch8_i22', 'ch8_p2', 'Distributed Architectures: Multiprocessor, Client–Server & Distributed Objects', 3),
  ('ch8_i23', 'ch8_p2', 'Real-Time Software Design & Component-Based Software Engineering', 4),
  ('ch8_p3', null, 'Testing, Cost Estimation, Quality & Configuration Management', 3),
  ('ch8_t3', 'ch8_p3', 'Testing Levels: Unit, Integration, Component, System & Acceptance', 1),
  ('ch8_i31', 'ch8_p3', 'Test Case Design, Test Automation & Testing Metrics', 2),
  ('ch8_i32', 'ch8_p3', 'Cost Estimation: Algorithmic Models, Duration & Staffing', 3),
  ('ch8_i33', 'ch8_p3', 'Software Quality Assurance, Reviews, Metrics, ISO & CMMI', 4),
  ('ch8_i34', 'ch8_p3', 'Configuration, Change, Version & Release Management', 5),
  ('ch8_p4', null, 'Object-Oriented Fundamentals & Analysis', 4),
  ('ch8_t4', 'ch8_p4', 'Object-Oriented Fundamentals, Models & Development Cycle', 1),
  ('ch8_i41', 'ch8_p4', 'The Requirement Process & Use Cases', 2),
  ('ch8_i42', 'ch8_p4', 'UML & Building the Conceptual (Domain) Model', 3),
  ('ch8_i43', 'ch8_p4', 'Associations, Attributes & Representing System Behaviour', 4),
  ('ch8_p5', null, 'Object-Oriented Design', 5),
  ('ch8_t5', 'ch8_p5', 'From Analysis to Design: Describing & Elaborating Use Cases', 1),
  ('ch8_i51', 'ch8_p5', 'Interaction Diagrams: Collaboration & Sequence', 2),
  ('ch8_i52', 'ch8_p5', 'Objects, Responsibilities & Design Patterns', 3),
  ('ch8_i53', 'ch8_p5', 'Determining Visibility & Design Class Diagrams', 4),
  ('ch8_p6', null, 'Object-Oriented Design Implementation', 6),
  ('ch8_t6', 'ch8_p6', 'Programming Process & Mapping Design to Code', 1),
  ('ch8_i61', 'ch8_p6', 'Class Definitions & Methods from Design Diagrams', 2),
  ('ch8_i62', 'ch8_p6', 'Exception & Error Handling', 3),
  ('ch8_p7', null, 'Quick Revision - Entire Chapter', 7),
  ('ch8_i71', 'ch8_p7', 'Models, Metrics, Notation & Key Facts', 1);

-- Old id -> new id; seq orders theory blocks when old topics merge.
create temp table id_map(old_id text primary key, new_id text, seq int) on commit drop;
insert into id_map values
  ('ch8_i01', 'ch8_t1', 1),
  ('ch8_i02', 'ch8_i11', 1),
  ('ch8_i03', 'ch8_t2', 1),
  ('ch8_i04', 'ch8_i21', 1),
  ('ch8_i05', 'ch8_t3', 1),
  ('ch8_i06', 'ch8_i34', 1),
  ('ch8_i07', 'ch8_t4', 1),
  ('ch8_i08', 'ch8_i41', 1),
  ('ch8_i09', 'ch8_i52', 1),
  ('ch8_i10', 'ch8_t6', 1);

do $$
declare missing text;
begin
  select string_agg(id, ', ') into missing
  from public.topics
  where chapter_id = 'ch8'
    and id not in (select old_id from id_map)
    and id not in (select id from drop_topics);
  if missing is not null then
    raise exception 'Unmapped ch8 topics: %', missing;
  end if;
end $$;

-- Stage through temporary topics.
insert into public.topics (id, chapter_id, title, description, icon, "order")
select distinct 'tmp_' || new_id, 'ch8', 'tmp', 'tmp', null, 0 from id_map;

update public.questions           x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;
update public.question_attempts   x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;
update public.flashcards          x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;
update public.formulas            x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;

create temp table progress_stage on commit drop as
select p.user_id, 'tmp_' || m.new_id as topic_id,
       bool_or(p.completed) as completed, max(p.completion_pct) as completion_pct, max(p.last_studied_at) as last_studied_at
from public.user_topic_progress p join id_map m on m.old_id = p.topic_id
group by p.user_id, m.new_id;
delete from public.user_topic_progress where topic_id in (select old_id from id_map);
insert into public.user_topic_progress (user_id, topic_id, completed, completion_pct, last_studied_at)
select user_id, topic_id, completed, completion_pct, last_studied_at from progress_stage;

create temp table theory_stage on commit drop as
select 'tmp_' || m.new_id as topic_id,
       coalesce(jsonb_agg(e.b order by m.seq, e.n) filter (where e.kind = 'concepts'), '[]'::jsonb) as concepts,
       coalesce(jsonb_agg(e.b order by m.seq, e.n) filter (where e.kind = 'formulas'), '[]'::jsonb) as formulas,
       coalesce(jsonb_agg(e.b order by m.seq, e.n) filter (where e.kind = 'notes'),    '[]'::jsonb) as notes
from public.theory_content t
join id_map m on m.old_id = t.topic_id
cross join lateral (
  select 'concepts' as kind, x.b, x.n from jsonb_array_elements(coalesce(t.concepts, '[]')) with ordinality x(b, n)
  union all
  select 'formulas', x.b, x.n from jsonb_array_elements(coalesce(t.formulas, '[]')) with ordinality x(b, n)
  union all
  select 'notes',    x.b, x.n from jsonb_array_elements(coalesce(t.notes, '[]'))    with ordinality x(b, n)
) e
group by m.new_id;
delete from public.theory_content where topic_id in (select old_id from id_map);
insert into public.theory_content (topic_id, concepts, formulas, notes)
select topic_id, concepts, formulas, notes from theory_stage;

-- Replace the old ch8 topics with the tree (parents first for the FK).
delete from public.topics where chapter_id = 'ch8' and id not like 'tmp\_%';
insert into public.topics (id, chapter_id, title, description, icon, "order", parent_topic_id)
select id, 'ch8', title, title, null, ord, parent from new_topics where parent is null;
insert into public.topics (id, chapter_id, title, description, icon, "order", parent_topic_id)
select id, 'ch8', title, title, null, ord, parent from new_topics where parent is not null;

update public.questions           set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch8\_%';
update public.question_attempts   set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch8\_%';
update public.flashcards          set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch8\_%';
update public.formulas            set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch8\_%';
update public.user_topic_progress set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch8\_%';
update public.theory_content      set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch8\_%';
delete from public.topics where id like 'tmp\_ch8\_%';

commit;

-- Verification (shown as the result)
select coalesce(p."order", t."order") as topic_no, coalesce(p.title, t.title) as topic, t.id, t.title as subtopic,
       (select count(*) from public.questions  q where q.topic_id = t.id) as questions,
       (select count(*) from public.flashcards f where f.topic_id = t.id) as flashcards,
       (select count(*) from public.formulas   f where f.topic_id = t.id) as formulas,
       (select coalesce(jsonb_array_length(c.concepts), 0) from public.theory_content c where c.topic_id = t.id) as concept_blocks
from public.topics t left join public.topics p on p.id = t.parent_topic_id
where t.chapter_id = 'ch8'
order by coalesce(p."order", t."order"), t.parent_topic_id nulls first, t."order";
