-- =====================================================================
-- CH4 restructure: Chapter -> Topic (parent) -> Subtopic
-- Generated by tools/gen_chapter_migration.mjs from supabase/content/ch4/tree.json
-- on 20260925. Same mechanics as the Chapter 1 migration:
--   * parent topics ch4_p1, ch4_p2, ch4_p3, ch4_p4, ch4_p5, ch4_p6, ch4_p7
--   * every existing ch4 topic re-pointed via tmp_ ids (old/new ids overlap)
--   * questions, flashcards, formulas, theory, progress and attempts follow
--   * dropped topics: none
-- Runs as one transaction; backups go to schema "backup".
-- =====================================================================

begin;

create schema if not exists backup;
create table backup.ch4_topics_20260925         as select * from public.topics              where chapter_id = 'ch4';
create table backup.ch4_theory_content_20260925 as select * from public.theory_content      where topic_id like 'ch4\_%';
create table backup.ch4_questions_20260925      as select * from public.questions           where chapter_id = 'ch4';
create table backup.ch4_question_options_20260925 as select o.* from public.question_options o join public.questions q on q.id = o.question_id where q.chapter_id = 'ch4';
create table backup.ch4_flashcards_20260925     as select * from public.flashcards          where chapter_id = 'ch4';
create table backup.ch4_flashcard_reviews_20260925 as select r.* from public.flashcard_reviews r join public.flashcards f on f.id = r.card_id where f.chapter_id = 'ch4';
create table backup.ch4_formulas_20260925       as select * from public.formulas            where chapter_id = 'ch4';
create table backup.ch4_progress_20260925       as select * from public.user_topic_progress where topic_id like 'ch4\_%';
create table backup.ch4_attempts_20260925       as select * from public.question_attempts   where chapter_id = 'ch4';

alter table public.topics add column if not exists parent_topic_id text references public.topics(id);
create index if not exists topics_parent_topic_id_idx on public.topics(parent_topic_id);

-- Dropped topics and everything attached to them.
create temp table drop_topics(id text primary key) on commit drop;
-- (none)
delete from public.question_attempts where topic_id in (select id from drop_topics)
   or question_id in (select id from public.questions where topic_id in (select id from drop_topics));
delete from public.question_options  where question_id in (select id from public.questions where topic_id in (select id from drop_topics));
delete from public.questions         where topic_id in (select id from drop_topics);
delete from public.flashcard_reviews where card_id in (select id from public.flashcards where topic_id in (select id from drop_topics));
delete from public.flashcards        where topic_id in (select id from drop_topics);
delete from public.formulas          where topic_id in (select id from drop_topics);
delete from public.theory_content    where topic_id in (select id from drop_topics);
delete from public.user_topic_progress where topic_id in (select id from drop_topics);

-- Final tree.
create temp table new_topics(id text primary key, parent text, title text, ord int) on commit drop;
insert into new_topics values
  ('ch4_p1', null, 'Control & Central Processing Units', 1),
  ('ch4_t1', 'ch4_p1', 'CPU Structure, ALU & Control Unit', 1),
  ('ch4_i11', 'ch4_p1', 'Microprogrammed Control: Control Memory & Microinstructions', 2),
  ('ch4_i12', 'ch4_p1', 'Instruction Formats, Addressing Modes & Data Manipulation', 3),
  ('ch4_i13', 'ch4_p1', 'RISC vs CISC', 4),
  ('ch4_i14', 'ch4_p1', 'Pipelining & Parallel Processing', 5),
  ('ch4_p2', null, 'Computer Arithmetic & Memory System', 2),
  ('ch4_t2', 'ch4_p2', 'Arithmetic & Logical Operations', 1),
  ('ch4_i21', 'ch4_p2', 'Memory Hierarchy, Internal & External Memory', 2),
  ('ch4_i22', 'ch4_p2', 'Cache Memory Principles & Design', 3),
  ('ch4_i23', 'ch4_p2', 'Memory Write Ability, Permanence & Composing Memory', 4),
  ('ch4_p3', null, 'Input-Output Organization & Multiprocessors', 3),
  ('ch4_t3', 'ch4_p3', 'Peripherals, I/O Modules & Interfaces', 1),
  ('ch4_i31', 'ch4_p3', 'Modes of Transfer & Direct Memory Access', 2),
  ('ch4_i32', 'ch4_p3', 'Multiprocessors & Interconnection Structures', 3),
  ('ch4_i33', 'ch4_p3', 'Inter-processor Communication & Synchronization', 4),
  ('ch4_p4', null, 'Hardware-Software Design of Embedded Systems', 4),
  ('ch4_t4', 'ch4_p4', 'Embedded Systems Overview & Classification', 1),
  ('ch4_i41', 'ch4_p4', 'Custom Single-Purpose Processor Design & Optimization', 2),
  ('ch4_i42', 'ch4_p4', 'General-Purpose Processors: Architecture, Operation & Programmer''s View', 3),
  ('ch4_i43', 'ch4_p4', 'Application-Specific Instruction-Set Processors', 4),
  ('ch4_p5', null, 'Real-Time Operating & Control Systems', 5),
  ('ch4_t5', 'ch4_p5', 'Operating System Basics: Tasks, Processes & Threads', 1),
  ('ch4_i51', 'ch4_p5', 'Multitasking & Task Scheduling', 2),
  ('ch4_i52', 'ch4_p5', 'Task Synchronization & Device Drivers', 3),
  ('ch4_i53', 'ch4_p5', 'Open-Loop & Closed-Loop Control Systems', 4),
  ('ch4_p6', null, 'Hardware Description Language & IC Technology', 6),
  ('ch4_t6', 'ch4_p6', 'VHDL Overview, Structure & Data Types', 1),
  ('ch4_i61', 'ch4_p6', 'Overflow & Data Representation in VHDL', 2),
  ('ch4_i62', 'ch4_p6', 'Combinational & Sequential Logic Design in VHDL', 3),
  ('ch4_i63', 'ch4_p6', 'Pipelining in VHDL & IC Technology', 4),
  ('ch4_p7', null, 'Quick Revision - Entire Chapter', 7),
  ('ch4_i71', 'ch4_p7', 'Key Facts & Formulas', 1);

-- Old id -> new id; seq orders theory blocks when old topics merge.
create temp table id_map(old_id text primary key, new_id text, seq int) on commit drop;
insert into id_map values
  ('ch4_i01', 'ch4_t1', 1),
  ('ch4_i02', 'ch4_i12', 1),
  ('ch4_i03', 'ch4_i14', 1),
  ('ch4_i04', 'ch4_t2', 1),
  ('ch4_i05', 'ch4_i21', 1),
  ('ch4_i06', 'ch4_i22', 1),
  ('ch4_i07', 'ch4_t3', 1),
  ('ch4_i08', 'ch4_i32', 1),
  ('ch4_i09', 'ch4_t4', 1),
  ('ch4_i10', 'ch4_i41', 1),
  ('ch4_i11', 'ch4_i51', 1),
  ('ch4_i12', 'ch4_i52', 1),
  ('ch4_i13', 'ch4_t6', 1),
  ('ch4_i14', 'ch4_i62', 1);

do $$
declare missing text;
begin
  select string_agg(id, ', ') into missing
  from public.topics
  where chapter_id = 'ch4'
    and id not in (select old_id from id_map)
    and id not in (select id from drop_topics);
  if missing is not null then
    raise exception 'Unmapped ch4 topics: %', missing;
  end if;
end $$;

-- Stage through temporary topics.
insert into public.topics (id, chapter_id, title, description, icon, "order")
select distinct 'tmp_' || new_id, 'ch4', 'tmp', 'tmp', null, 0 from id_map;

update public.questions           x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;
update public.question_attempts   x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;
update public.flashcards          x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;
update public.formulas            x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;

create temp table progress_stage on commit drop as
select p.user_id, 'tmp_' || m.new_id as topic_id,
       bool_or(p.completed) as completed, max(p.completion_pct) as completion_pct, max(p.last_studied_at) as last_studied_at
from public.user_topic_progress p join id_map m on m.old_id = p.topic_id
group by p.user_id, m.new_id;
delete from public.user_topic_progress where topic_id in (select old_id from id_map);
insert into public.user_topic_progress (user_id, topic_id, completed, completion_pct, last_studied_at)
select user_id, topic_id, completed, completion_pct, last_studied_at from progress_stage;

create temp table theory_stage on commit drop as
select 'tmp_' || m.new_id as topic_id,
       coalesce(jsonb_agg(e.b order by m.seq, e.n) filter (where e.kind = 'concepts'), '[]'::jsonb) as concepts,
       coalesce(jsonb_agg(e.b order by m.seq, e.n) filter (where e.kind = 'formulas'), '[]'::jsonb) as formulas,
       coalesce(jsonb_agg(e.b order by m.seq, e.n) filter (where e.kind = 'notes'),    '[]'::jsonb) as notes
from public.theory_content t
join id_map m on m.old_id = t.topic_id
cross join lateral (
  select 'concepts' as kind, x.b, x.n from jsonb_array_elements(coalesce(t.concepts, '[]')) with ordinality x(b, n)
  union all
  select 'formulas', x.b, x.n from jsonb_array_elements(coalesce(t.formulas, '[]')) with ordinality x(b, n)
  union all
  select 'notes',    x.b, x.n from jsonb_array_elements(coalesce(t.notes, '[]'))    with ordinality x(b, n)
) e
group by m.new_id;
delete from public.theory_content where topic_id in (select old_id from id_map);
insert into public.theory_content (topic_id, concepts, formulas, notes)
select topic_id, concepts, formulas, notes from theory_stage;

-- Replace the old ch4 topics with the tree (parents first for the FK).
delete from public.topics where chapter_id = 'ch4' and id not like 'tmp\_%';
insert into public.topics (id, chapter_id, title, description, icon, "order", parent_topic_id)
select id, 'ch4', title, title, null, ord, parent from new_topics where parent is null;
insert into public.topics (id, chapter_id, title, description, icon, "order", parent_topic_id)
select id, 'ch4', title, title, null, ord, parent from new_topics where parent is not null;

update public.questions           set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch4\_%';
update public.question_attempts   set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch4\_%';
update public.flashcards          set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch4\_%';
update public.formulas            set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch4\_%';
update public.user_topic_progress set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch4\_%';
update public.theory_content      set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch4\_%';
delete from public.topics where id like 'tmp\_ch4\_%';

commit;

-- Verification (shown as the result)
select coalesce(p."order", t."order") as topic_no, coalesce(p.title, t.title) as topic, t.id, t.title as subtopic,
       (select count(*) from public.questions  q where q.topic_id = t.id) as questions,
       (select count(*) from public.flashcards f where f.topic_id = t.id) as flashcards,
       (select count(*) from public.formulas   f where f.topic_id = t.id) as formulas,
       (select coalesce(jsonb_array_length(c.concepts), 0) from public.theory_content c where c.topic_id = t.id) as concept_blocks
from public.topics t left join public.topics p on p.id = t.parent_topic_id
where t.chapter_id = 'ch4'
order by coalesce(p."order", t."order"), t.parent_topic_id nulls first, t."order";
