-- =====================================================================
-- CH3 restructure: Chapter -> Topic (parent) -> Subtopic
-- Generated by tools/gen_chapter_migration.mjs from supabase/content/ch3/tree.json
-- on 20260925. Same mechanics as the Chapter 1 migration:
--   * parent topics ch3_p1, ch3_p2, ch3_p3, ch3_p4, ch3_p5, ch3_p6, ch3_p7
--   * every existing ch3 topic re-pointed via tmp_ ids (old/new ids overlap)
--   * questions, flashcards, formulas, theory, progress and attempts follow
--   * dropped topics: none
-- Runs as one transaction; backups go to schema "backup".
-- =====================================================================

begin;

create schema if not exists backup;
create table backup.ch3_topics_20260925         as select * from public.topics              where chapter_id = 'ch3';
create table backup.ch3_theory_content_20260925 as select * from public.theory_content      where topic_id like 'ch3\_%';
create table backup.ch3_questions_20260925      as select * from public.questions           where chapter_id = 'ch3';
create table backup.ch3_question_options_20260925 as select o.* from public.question_options o join public.questions q on q.id = o.question_id where q.chapter_id = 'ch3';
create table backup.ch3_flashcards_20260925     as select * from public.flashcards          where chapter_id = 'ch3';
create table backup.ch3_flashcard_reviews_20260925 as select r.* from public.flashcard_reviews r join public.flashcards f on f.id = r.card_id where f.chapter_id = 'ch3';
create table backup.ch3_formulas_20260925       as select * from public.formulas            where chapter_id = 'ch3';
create table backup.ch3_progress_20260925       as select * from public.user_topic_progress where topic_id like 'ch3\_%';
create table backup.ch3_attempts_20260925       as select * from public.question_attempts   where chapter_id = 'ch3';

alter table public.topics add column if not exists parent_topic_id text references public.topics(id);
create index if not exists topics_parent_topic_id_idx on public.topics(parent_topic_id);

-- Dropped topics and everything attached to them.
create temp table drop_topics(id text primary key) on commit drop;
-- (none)
delete from public.question_attempts where topic_id in (select id from drop_topics)
   or question_id in (select id from public.questions where topic_id in (select id from drop_topics));
delete from public.question_options  where question_id in (select id from public.questions where topic_id in (select id from drop_topics));
delete from public.questions         where topic_id in (select id from drop_topics);
delete from public.flashcard_reviews where card_id in (select id from public.flashcards where topic_id in (select id from drop_topics));
delete from public.flashcards        where topic_id in (select id from drop_topics);
delete from public.formulas          where topic_id in (select id from drop_topics);
delete from public.theory_content    where topic_id in (select id from drop_topics);
delete from public.user_topic_progress where topic_id in (select id from drop_topics);

-- Final tree.
create temp table new_topics(id text primary key, parent text, title text, ord int) on commit drop;
insert into new_topics values
  ('ch3_p1', null, 'Introduction to C Programming', 1),
  ('ch3_t1', 'ch3_p1', 'C Tokens, Identifiers & Data Types', 1),
  ('ch3_i11', 'ch3_p1', 'Operators & Precedence', 2),
  ('ch3_i12', 'ch3_p1', 'Formatted & Unformatted Input/Output', 3),
  ('ch3_i13', 'ch3_p1', 'Control Statements & Looping', 4),
  ('ch3_i14', 'ch3_p1', 'User-Defined & Recursive Functions', 5),
  ('ch3_i15', 'ch3_p1', 'Arrays & String Manipulation', 6),
  ('ch3_p2', null, 'Pointers, Structures & Data Files in C', 2),
  ('ch3_t2', 'ch3_p2', 'Pointers & Pointer Arithmetic', 1),
  ('ch3_i21', 'ch3_p2', 'Pointers with Arrays & Functions', 2),
  ('ch3_i22', 'ch3_p2', 'Structures & Unions', 3),
  ('ch3_i23', 'ch3_p2', 'Structures with Pointers, Arrays & Functions', 4),
  ('ch3_i24', 'ch3_p2', 'File Operations & Access Methods', 5),
  ('ch3_p3', null, 'C++ Constructs: Objects & Classes', 3),
  ('ch3_t3', 'ch3_p3', 'Namespaces, Function Overloading, Inline & Default Arguments', 1),
  ('ch3_i31', 'ch3_p3', 'Classes, Objects & Access Specifiers', 2),
  ('ch3_i32', 'ch3_p3', 'Constructors, Destructors & Dynamic Objects', 3),
  ('ch3_i33', 'ch3_p3', 'Static Members, const, this & Friends', 4),
  ('ch3_p4', null, 'Features of Object-Oriented Programming', 4),
  ('ch3_t4', 'ch3_p4', 'Operator Overloading', 1),
  ('ch3_i41', 'ch3_p4', 'Data Conversion', 2),
  ('ch3_i42', 'ch3_p4', 'Inheritance: Types, Constructors & Destructors', 3),
  ('ch3_p5', null, 'Virtual Functions & File Handling', 5),
  ('ch3_t5', 'ch3_p5', 'Virtual Functions, Dynamic Binding & Abstract Classes', 1),
  ('ch3_i51', 'ch3_p5', 'C++ Streams & Formatted Console I/O', 2),
  ('ch3_i52', 'ch3_p5', 'C++ File Handling', 3),
  ('ch3_p6', null, 'Generic Programming & Exception Handling', 6),
  ('ch3_t6', 'ch3_p6', 'Function & Class Templates', 1),
  ('ch3_i61', 'ch3_p6', 'Standard Template Library (STL)', 2),
  ('ch3_i62', 'ch3_p6', 'Exception Handling', 3),
  ('ch3_p7', null, 'Quick Revision - Entire Chapter', 7),
  ('ch3_i71', 'ch3_p7', 'Key Facts & Syntax Cheat-Sheet', 1);

-- Old id -> new id; seq orders theory blocks when old topics merge.
create temp table id_map(old_id text primary key, new_id text, seq int) on commit drop;
insert into id_map values
  ('ch3_t1', 'ch3_t1', 1),
  ('ch3_i12', 'ch3_t1', 2),
  ('ch3_t2', 'ch3_i11', 1),
  ('ch3_i13', 'ch3_i12', 1),
  ('ch3_t3', 'ch3_i13', 1),
  ('ch3_t4', 'ch3_i13', 2),
  ('ch3_t5', 'ch3_i14', 1),
  ('ch3_t6', 'ch3_i15', 1),
  ('ch3_t7', 'ch3_t2', 1),
  ('ch3_t8', 'ch3_i22', 1),
  ('ch3_i14', 'ch3_i22', 2),
  ('ch3_i15', 'ch3_i24', 1),
  ('ch3_t9', 'ch3_i31', 1),
  ('ch3_t10', 'ch3_i32', 1),
  ('ch3_i16', 'ch3_i33', 1),
  ('ch3_i17', 'ch3_t4', 1),
  ('ch3_t11', 'ch3_i42', 1),
  ('ch3_i18', 'ch3_i52', 1),
  ('ch3_i19', 'ch3_t6', 1),
  ('ch3_i20', 'ch3_i62', 1);

do $$
declare missing text;
begin
  select string_agg(id, ', ') into missing
  from public.topics
  where chapter_id = 'ch3'
    and id not in (select old_id from id_map)
    and id not in (select id from drop_topics);
  if missing is not null then
    raise exception 'Unmapped ch3 topics: %', missing;
  end if;
end $$;

-- Stage through temporary topics.
insert into public.topics (id, chapter_id, title, description, icon, "order")
select distinct 'tmp_' || new_id, 'ch3', 'tmp', 'tmp', null, 0 from id_map;

update public.questions           x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;
update public.question_attempts   x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;
update public.flashcards          x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;
update public.formulas            x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;

create temp table progress_stage on commit drop as
select p.user_id, 'tmp_' || m.new_id as topic_id,
       bool_or(p.completed) as completed, max(p.completion_pct) as completion_pct, max(p.last_studied_at) as last_studied_at
from public.user_topic_progress p join id_map m on m.old_id = p.topic_id
group by p.user_id, m.new_id;
delete from public.user_topic_progress where topic_id in (select old_id from id_map);
insert into public.user_topic_progress (user_id, topic_id, completed, completion_pct, last_studied_at)
select user_id, topic_id, completed, completion_pct, last_studied_at from progress_stage;

create temp table theory_stage on commit drop as
select 'tmp_' || m.new_id as topic_id,
       coalesce(jsonb_agg(e.b order by m.seq, e.n) filter (where e.kind = 'concepts'), '[]'::jsonb) as concepts,
       coalesce(jsonb_agg(e.b order by m.seq, e.n) filter (where e.kind = 'formulas'), '[]'::jsonb) as formulas,
       coalesce(jsonb_agg(e.b order by m.seq, e.n) filter (where e.kind = 'notes'),    '[]'::jsonb) as notes
from public.theory_content t
join id_map m on m.old_id = t.topic_id
cross join lateral (
  select 'concepts' as kind, x.b, x.n from jsonb_array_elements(coalesce(t.concepts, '[]')) with ordinality x(b, n)
  union all
  select 'formulas', x.b, x.n from jsonb_array_elements(coalesce(t.formulas, '[]')) with ordinality x(b, n)
  union all
  select 'notes',    x.b, x.n from jsonb_array_elements(coalesce(t.notes, '[]'))    with ordinality x(b, n)
) e
group by m.new_id;
delete from public.theory_content where topic_id in (select old_id from id_map);
insert into public.theory_content (topic_id, concepts, formulas, notes)
select topic_id, concepts, formulas, notes from theory_stage;

-- Replace the old ch3 topics with the tree (parents first for the FK).
delete from public.topics where chapter_id = 'ch3' and id not like 'tmp\_%';
insert into public.topics (id, chapter_id, title, description, icon, "order", parent_topic_id)
select id, 'ch3', title, title, null, ord, parent from new_topics where parent is null;
insert into public.topics (id, chapter_id, title, description, icon, "order", parent_topic_id)
select id, 'ch3', title, title, null, ord, parent from new_topics where parent is not null;

update public.questions           set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch3\_%';
update public.question_attempts   set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch3\_%';
update public.flashcards          set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch3\_%';
update public.formulas            set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch3\_%';
update public.user_topic_progress set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch3\_%';
update public.theory_content      set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch3\_%';
delete from public.topics where id like 'tmp\_ch3\_%';

commit;

-- Verification (shown as the result)
select coalesce(p."order", t."order") as topic_no, coalesce(p.title, t.title) as topic, t.id, t.title as subtopic,
       (select count(*) from public.questions  q where q.topic_id = t.id) as questions,
       (select count(*) from public.flashcards f where f.topic_id = t.id) as flashcards,
       (select count(*) from public.formulas   f where f.topic_id = t.id) as formulas,
       (select coalesce(jsonb_array_length(c.concepts), 0) from public.theory_content c where c.topic_id = t.id) as concept_blocks
from public.topics t left join public.topics p on p.id = t.parent_topic_id
where t.chapter_id = 'ch3'
order by coalesce(p."order", t."order"), t.parent_topic_id nulls first, t."order";
