-- =====================================================================
-- CH7 restructure: Chapter -> Topic (parent) -> Subtopic
-- Generated by tools/gen_chapter_migration.mjs from supabase/content/ch7/tree.json
-- on 20260925. Same mechanics as the Chapter 1 migration:
--   * parent topics ch7_p1, ch7_p2, ch7_p3, ch7_p4, ch7_p5, ch7_p6, ch7_p7
--   * every existing ch7 topic re-pointed via tmp_ ids (old/new ids overlap)
--   * questions, flashcards, formulas, theory, progress and attempts follow
--   * dropped topics: none
-- Runs as one transaction; backups go to schema "backup".
-- =====================================================================

begin;

create schema if not exists backup;
create table backup.ch7_topics_20260925         as select * from public.topics              where chapter_id = 'ch7';
create table backup.ch7_theory_content_20260925 as select * from public.theory_content      where topic_id like 'ch7\_%';
create table backup.ch7_questions_20260925      as select * from public.questions           where chapter_id = 'ch7';
create table backup.ch7_question_options_20260925 as select o.* from public.question_options o join public.questions q on q.id = o.question_id where q.chapter_id = 'ch7';
create table backup.ch7_flashcards_20260925     as select * from public.flashcards          where chapter_id = 'ch7';
create table backup.ch7_flashcard_reviews_20260925 as select r.* from public.flashcard_reviews r join public.flashcards f on f.id = r.card_id where f.chapter_id = 'ch7';
create table backup.ch7_formulas_20260925       as select * from public.formulas            where chapter_id = 'ch7';
create table backup.ch7_progress_20260925       as select * from public.user_topic_progress where topic_id like 'ch7\_%';
create table backup.ch7_attempts_20260925       as select * from public.question_attempts   where chapter_id = 'ch7';

alter table public.topics add column if not exists parent_topic_id text references public.topics(id);
create index if not exists topics_parent_topic_id_idx on public.topics(parent_topic_id);

-- Dropped topics and everything attached to them.
create temp table drop_topics(id text primary key) on commit drop;
-- (none)
delete from public.question_attempts where topic_id in (select id from drop_topics)
   or question_id in (select id from public.questions where topic_id in (select id from drop_topics));
delete from public.question_options  where question_id in (select id from public.questions where topic_id in (select id from drop_topics));
delete from public.questions         where topic_id in (select id from drop_topics);
delete from public.flashcard_reviews where card_id in (select id from public.flashcards where topic_id in (select id from drop_topics));
delete from public.flashcards        where topic_id in (select id from drop_topics);
delete from public.formulas          where topic_id in (select id from drop_topics);
delete from public.theory_content    where topic_id in (select id from drop_topics);
delete from public.user_topic_progress where topic_id in (select id from drop_topics);

-- Final tree.
create temp table new_topics(id text primary key, parent text, title text, ord int) on commit drop;
insert into new_topics values
  ('ch7_p1', null, 'Data Structures, Lists & Trees', 1),
  ('ch7_t1', 'ch7_p1', 'Data Types, ADTs & Algorithm Analysis', 1),
  ('ch7_i11', 'ch7_p1', 'Stacks & Their Applications', 2),
  ('ch7_i12', 'ch7_p1', 'Queues & List Implementations', 3),
  ('ch7_i13', 'ch7_p1', 'Linked Lists: Singly, Doubly & Circular', 4),
  ('ch7_i14', 'ch7_p1', 'Trees: Binary Trees, Traversals & Binary Search Trees', 5),
  ('ch7_i15', 'ch7_p1', 'AVL Balanced Trees', 6),
  ('ch7_p2', null, 'Sorting, Searching & Graphs', 2),
  ('ch7_t2', 'ch7_p2', 'Sorting: Insertion, Selection & Exchange Sorts', 1),
  ('ch7_i21', 'ch7_p2', 'Merge, Radix, Shell & Heap Sort', 2),
  ('ch7_i22', 'ch7_p2', 'Searching & Hashing', 3),
  ('ch7_i23', 'ch7_p2', 'Graphs: Representation, Traversal & Transitive Closure', 4),
  ('ch7_i24', 'ch7_p2', 'Topological Sort, Minimum Spanning Trees & Shortest Paths', 5),
  ('ch7_p3', null, 'Data Models, Normalization & SQL', 3),
  ('ch7_t3', 'ch7_p3', 'Data Abstraction, Schemas & the E-R Model', 1),
  ('ch7_i31', 'ch7_p3', 'Keys, Integrity Constraints & Functional Dependencies', 2),
  ('ch7_i32', 'ch7_p3', 'Normalization: 1NF, 2NF, 3NF & BCNF', 3),
  ('ch7_i33', 'ch7_p3', 'SQL: DDL, DML, Views, Assertions & Triggers', 4),
  ('ch7_i34', 'ch7_p3', 'Relational Algebra, Query Processing & Optimization', 5),
  ('ch7_p4', null, 'Transactions, Concurrency Control & Crash Recovery', 4),
  ('ch7_t4', 'ch7_p4', 'Transactions, ACID Properties & Serializability', 1),
  ('ch7_i41', 'ch7_p4', 'Lock-Based Protocols & Deadlock Handling', 2),
  ('ch7_i42', 'ch7_p4', 'Failure Classification & Log-Based Recovery', 3),
  ('ch7_p5', null, 'Operating Systems & Process Management', 5),
  ('ch7_t5', 'ch7_p5', 'OS Evolution, Types, Structure & Services', 1),
  ('ch7_i51', 'ch7_p5', 'Processes, Threads & CPU Scheduling', 2),
  ('ch7_i52', 'ch7_p5', 'Concurrency: Critical Sections, Semaphores, Mutexes & Monitors', 3),
  ('ch7_i53', 'ch7_p5', 'Classical Problems of Synchronization', 4),
  ('ch7_p6', null, 'Memory Management, File Systems & Administration', 6),
  ('ch7_t6', 'ch7_p6', 'Memory Management: Addresses, Swapping & Free Space', 1),
  ('ch7_i61', 'ch7_p6', 'Virtual Memory, Demand Paging & Page Replacement', 2),
  ('ch7_i62', 'ch7_p6', 'Files, Directories & File-System Implementation', 3),
  ('ch7_i63', 'ch7_p6', 'Allocation, Fragmentation, Disk Mapping & File-System Performance', 4),
  ('ch7_i64', 'ch7_p6', 'System Administration: Users, Start-up & Shutdown', 5),
  ('ch7_p7', null, 'Quick Revision - Entire Chapter', 7),
  ('ch7_i71', 'ch7_p7', 'Complexities, Rules & Formulas Cheat-Sheet', 1);

-- Old id -> new id; seq orders theory blocks when old topics merge.
create temp table id_map(old_id text primary key, new_id text, seq int) on commit drop;
insert into id_map values
  ('ch7_i01', 'ch7_t1', 1),
  ('ch7_i02', 'ch7_i11', 1),
  ('ch7_i03', 'ch7_i13', 1),
  ('ch7_i04', 'ch7_t2', 1),
  ('ch7_i05', 'ch7_i23', 1),
  ('ch7_i06', 'ch7_t3', 1),
  ('ch7_i07', 'ch7_i32', 1),
  ('ch7_i08', 'ch7_t4', 1),
  ('ch7_i09', 'ch7_i42', 1),
  ('ch7_i10', 'ch7_t5', 1),
  ('ch7_i11', 'ch7_i52', 1),
  ('ch7_i12', 'ch7_t6', 1),
  ('ch7_i13', 'ch7_i62', 1);

do $$
declare missing text;
begin
  select string_agg(id, ', ') into missing
  from public.topics
  where chapter_id = 'ch7'
    and id not in (select old_id from id_map)
    and id not in (select id from drop_topics);
  if missing is not null then
    raise exception 'Unmapped ch7 topics: %', missing;
  end if;
end $$;

-- Stage through temporary topics.
insert into public.topics (id, chapter_id, title, description, icon, "order")
select distinct 'tmp_' || new_id, 'ch7', 'tmp', 'tmp', null, 0 from id_map;

update public.questions           x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;
update public.question_attempts   x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;
update public.flashcards          x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;
update public.formulas            x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;

create temp table progress_stage on commit drop as
select p.user_id, 'tmp_' || m.new_id as topic_id,
       bool_or(p.completed) as completed, max(p.completion_pct) as completion_pct, max(p.last_studied_at) as last_studied_at
from public.user_topic_progress p join id_map m on m.old_id = p.topic_id
group by p.user_id, m.new_id;
delete from public.user_topic_progress where topic_id in (select old_id from id_map);
insert into public.user_topic_progress (user_id, topic_id, completed, completion_pct, last_studied_at)
select user_id, topic_id, completed, completion_pct, last_studied_at from progress_stage;

create temp table theory_stage on commit drop as
select 'tmp_' || m.new_id as topic_id,
       coalesce(jsonb_agg(e.b order by m.seq, e.n) filter (where e.kind = 'concepts'), '[]'::jsonb) as concepts,
       coalesce(jsonb_agg(e.b order by m.seq, e.n) filter (where e.kind = 'formulas'), '[]'::jsonb) as formulas,
       coalesce(jsonb_agg(e.b order by m.seq, e.n) filter (where e.kind = 'notes'),    '[]'::jsonb) as notes
from public.theory_content t
join id_map m on m.old_id = t.topic_id
cross join lateral (
  select 'concepts' as kind, x.b, x.n from jsonb_array_elements(coalesce(t.concepts, '[]')) with ordinality x(b, n)
  union all
  select 'formulas', x.b, x.n from jsonb_array_elements(coalesce(t.formulas, '[]')) with ordinality x(b, n)
  union all
  select 'notes',    x.b, x.n from jsonb_array_elements(coalesce(t.notes, '[]'))    with ordinality x(b, n)
) e
group by m.new_id;
delete from public.theory_content where topic_id in (select old_id from id_map);
insert into public.theory_content (topic_id, concepts, formulas, notes)
select topic_id, concepts, formulas, notes from theory_stage;

-- Replace the old ch7 topics with the tree (parents first for the FK).
delete from public.topics where chapter_id = 'ch7' and id not like 'tmp\_%';
insert into public.topics (id, chapter_id, title, description, icon, "order", parent_topic_id)
select id, 'ch7', title, title, null, ord, parent from new_topics where parent is null;
insert into public.topics (id, chapter_id, title, description, icon, "order", parent_topic_id)
select id, 'ch7', title, title, null, ord, parent from new_topics where parent is not null;

update public.questions           set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch7\_%';
update public.question_attempts   set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch7\_%';
update public.flashcards          set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch7\_%';
update public.formulas            set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch7\_%';
update public.user_topic_progress set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch7\_%';
update public.theory_content      set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch7\_%';
delete from public.topics where id like 'tmp\_ch7\_%';

commit;

-- Verification (shown as the result)
select coalesce(p."order", t."order") as topic_no, coalesce(p.title, t.title) as topic, t.id, t.title as subtopic,
       (select count(*) from public.questions  q where q.topic_id = t.id) as questions,
       (select count(*) from public.flashcards f where f.topic_id = t.id) as flashcards,
       (select count(*) from public.formulas   f where f.topic_id = t.id) as formulas,
       (select coalesce(jsonb_array_length(c.concepts), 0) from public.theory_content c where c.topic_id = t.id) as concept_blocks
from public.topics t left join public.topics p on p.id = t.parent_topic_id
where t.chapter_id = 'ch7'
order by coalesce(p."order", t."order"), t.parent_topic_id nulls first, t."order";
