-- =====================================================================
-- CH5 restructure: Chapter -> Topic (parent) -> Subtopic
-- Generated by tools/gen_chapter_migration.mjs from supabase/content/ch5/tree.json
-- on 20260925. Same mechanics as the Chapter 1 migration:
--   * parent topics ch5_p1, ch5_p2, ch5_p3, ch5_p4, ch5_p5, ch5_p6, ch5_p7
--   * every existing ch5 topic re-pointed via tmp_ ids (old/new ids overlap)
--   * questions, flashcards, formulas, theory, progress and attempts follow
--   * dropped topics: none
-- Runs as one transaction; backups go to schema "backup".
-- =====================================================================

begin;

create schema if not exists backup;
create table backup.ch5_topics_20260925         as select * from public.topics              where chapter_id = 'ch5';
create table backup.ch5_theory_content_20260925 as select * from public.theory_content      where topic_id like 'ch5\_%';
create table backup.ch5_questions_20260925      as select * from public.questions           where chapter_id = 'ch5';
create table backup.ch5_question_options_20260925 as select o.* from public.question_options o join public.questions q on q.id = o.question_id where q.chapter_id = 'ch5';
create table backup.ch5_flashcards_20260925     as select * from public.flashcards          where chapter_id = 'ch5';
create table backup.ch5_flashcard_reviews_20260925 as select r.* from public.flashcard_reviews r join public.flashcards f on f.id = r.card_id where f.chapter_id = 'ch5';
create table backup.ch5_formulas_20260925       as select * from public.formulas            where chapter_id = 'ch5';
create table backup.ch5_progress_20260925       as select * from public.user_topic_progress where topic_id like 'ch5\_%';
create table backup.ch5_attempts_20260925       as select * from public.question_attempts   where chapter_id = 'ch5';

alter table public.topics add column if not exists parent_topic_id text references public.topics(id);
create index if not exists topics_parent_topic_id_idx on public.topics(parent_topic_id);

-- Dropped topics and everything attached to them.
create temp table drop_topics(id text primary key) on commit drop;
-- (none)
delete from public.question_attempts where topic_id in (select id from drop_topics)
   or question_id in (select id from public.questions where topic_id in (select id from drop_topics));
delete from public.question_options  where question_id in (select id from public.questions where topic_id in (select id from drop_topics));
delete from public.questions         where topic_id in (select id from drop_topics);
delete from public.flashcard_reviews where card_id in (select id from public.flashcards where topic_id in (select id from drop_topics));
delete from public.flashcards        where topic_id in (select id from drop_topics);
delete from public.formulas          where topic_id in (select id from drop_topics);
delete from public.theory_content    where topic_id in (select id from drop_topics);
delete from public.user_topic_progress where topic_id in (select id from drop_topics);

-- Final tree.
create temp table new_topics(id text primary key, parent text, title text, ord int) on commit drop;
insert into new_topics values
  ('ch5_p1', null, 'Computer Networks & Physical Layer', 1),
  ('ch5_t1', 'ch5_p1', 'Networking Models, Protocols & Standards (OSI & TCP/IP)', 1),
  ('ch5_i11', 'ch5_p1', 'Networking Devices: Hubs, Bridges, Switches & Routers', 2),
  ('ch5_i12', 'ch5_p1', 'Transmission Media', 3),
  ('ch5_p2', null, 'Data Link Layer', 2),
  ('ch5_t2', 'ch5_p2', 'Data Link Services, Error Detection & Correction', 1),
  ('ch5_i21', 'ch5_p2', 'Flow Control & Data Link Protocols', 2),
  ('ch5_i22', 'ch5_p2', 'Multiple Access Protocols & CSMA/CD', 3),
  ('ch5_i23', 'ch5_p2', 'LAN Standards: Ethernet, Token Bus, Token Ring & Wireless LANs', 4),
  ('ch5_i24', 'ch5_p2', 'LAN Addressing, ARP, PPP & WAN Protocols', 5),
  ('ch5_p3', null, 'Network Layer', 3),
  ('ch5_t3', 'ch5_p3', 'IPv4 Addressing, Classes & Subnetting', 1),
  ('ch5_i31', 'ch5_p3', 'Routing Algorithms', 2),
  ('ch5_i32', 'ch5_p3', 'Routing Protocols: RIP, OSPF, BGP & Multicast', 3),
  ('ch5_i33', 'ch5_p3', 'Network-Layer Protocols: IP, ARP, RARP & ICMP', 4),
  ('ch5_i34', 'ch5_p3', 'IPv6: Packet Format, Extension Headers & Transition', 5),
  ('ch5_p4', null, 'Transport Layer', 4),
  ('ch5_t4', 'ch5_p4', 'Transport Service, TCP & UDP', 1),
  ('ch5_i41', 'ch5_p4', 'Ports, Sockets, Multiplexing & Demultiplexing', 2),
  ('ch5_i42', 'ch5_p4', 'Connection Establishment & Release', 3),
  ('ch5_i43', 'ch5_p4', 'Flow Control, Buffering & Congestion Control', 4),
  ('ch5_p5', null, 'Application Layer', 5),
  ('ch5_t5', 'ch5_p5', 'The Web: HTTP & HTTPS', 1),
  ('ch5_i51', 'ch5_p5', 'File Transfer & Remote Access: FTP, PuTTY & WinSCP', 2),
  ('ch5_i52', 'ch5_p5', 'Electronic Mail', 3),
  ('ch5_i53', 'ch5_p5', 'DNS & Peer-to-Peer Applications', 4),
  ('ch5_i54', 'ch5_p5', 'Socket Programming & Application Servers', 5),
  ('ch5_i55', 'ch5_p5', 'Traffic Analysers: MRTG, PRTG, SNMP, Packet Tracer & Wireshark', 6),
  ('ch5_p6', null, 'Network Security', 6),
  ('ch5_t6', 'ch5_p6', 'Types of Security & Security Attacks', 1),
  ('ch5_i61', 'ch5_p6', 'Principles of Cryptography & the RSA Algorithm', 2),
  ('ch5_i62', 'ch5_p6', 'Digital Signatures & Securing E-mail (PGP)', 3),
  ('ch5_i63', 'ch5_p6', 'Securing TCP (SSL/TLS) & Network Layer (IPsec, VPN)', 4),
  ('ch5_i64', 'ch5_p6', 'Wireless LAN Security & Firewalls', 5),
  ('ch5_p7', null, 'Quick Revision - Entire Chapter', 7),
  ('ch5_i71', 'ch5_p7', 'Key Facts, Numbers & Port Table', 1);

-- Old id -> new id; seq orders theory blocks when old topics merge.
create temp table id_map(old_id text primary key, new_id text, seq int) on commit drop;
insert into id_map values
  ('ch5_i01', 'ch5_t1', 1),
  ('ch5_i02', 'ch5_i11', 1),
  ('ch5_i03', 'ch5_t2', 1),
  ('ch5_i04', 'ch5_i22', 1),
  ('ch5_i05', 'ch5_t3', 1),
  ('ch5_i06', 'ch5_i31', 1),
  ('ch5_i07', 'ch5_i34', 1),
  ('ch5_i08', 'ch5_t4', 1),
  ('ch5_i09', 'ch5_i41', 1),
  ('ch5_i10', 'ch5_t5', 1),
  ('ch5_i11', 'ch5_i53', 1),
  ('ch5_i12', 'ch5_t6', 1),
  ('ch5_i13', 'ch5_i61', 1),
  ('ch5_i14', 'ch5_i63', 1);

do $$
declare missing text;
begin
  select string_agg(id, ', ') into missing
  from public.topics
  where chapter_id = 'ch5'
    and id not in (select old_id from id_map)
    and id not in (select id from drop_topics);
  if missing is not null then
    raise exception 'Unmapped ch5 topics: %', missing;
  end if;
end $$;

-- Stage through temporary topics.
insert into public.topics (id, chapter_id, title, description, icon, "order")
select distinct 'tmp_' || new_id, 'ch5', 'tmp', 'tmp', null, 0 from id_map;

update public.questions           x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;
update public.question_attempts   x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;
update public.flashcards          x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;
update public.formulas            x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;

create temp table progress_stage on commit drop as
select p.user_id, 'tmp_' || m.new_id as topic_id,
       bool_or(p.completed) as completed, max(p.completion_pct) as completion_pct, max(p.last_studied_at) as last_studied_at
from public.user_topic_progress p join id_map m on m.old_id = p.topic_id
group by p.user_id, m.new_id;
delete from public.user_topic_progress where topic_id in (select old_id from id_map);
insert into public.user_topic_progress (user_id, topic_id, completed, completion_pct, last_studied_at)
select user_id, topic_id, completed, completion_pct, last_studied_at from progress_stage;

create temp table theory_stage on commit drop as
select 'tmp_' || m.new_id as topic_id,
       coalesce(jsonb_agg(e.b order by m.seq, e.n) filter (where e.kind = 'concepts'), '[]'::jsonb) as concepts,
       coalesce(jsonb_agg(e.b order by m.seq, e.n) filter (where e.kind = 'formulas'), '[]'::jsonb) as formulas,
       coalesce(jsonb_agg(e.b order by m.seq, e.n) filter (where e.kind = 'notes'),    '[]'::jsonb) as notes
from public.theory_content t
join id_map m on m.old_id = t.topic_id
cross join lateral (
  select 'concepts' as kind, x.b, x.n from jsonb_array_elements(coalesce(t.concepts, '[]')) with ordinality x(b, n)
  union all
  select 'formulas', x.b, x.n from jsonb_array_elements(coalesce(t.formulas, '[]')) with ordinality x(b, n)
  union all
  select 'notes',    x.b, x.n from jsonb_array_elements(coalesce(t.notes, '[]'))    with ordinality x(b, n)
) e
group by m.new_id;
delete from public.theory_content where topic_id in (select old_id from id_map);
insert into public.theory_content (topic_id, concepts, formulas, notes)
select topic_id, concepts, formulas, notes from theory_stage;

-- Replace the old ch5 topics with the tree (parents first for the FK).
delete from public.topics where chapter_id = 'ch5' and id not like 'tmp\_%';
insert into public.topics (id, chapter_id, title, description, icon, "order", parent_topic_id)
select id, 'ch5', title, title, null, ord, parent from new_topics where parent is null;
insert into public.topics (id, chapter_id, title, description, icon, "order", parent_topic_id)
select id, 'ch5', title, title, null, ord, parent from new_topics where parent is not null;

update public.questions           set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch5\_%';
update public.question_attempts   set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch5\_%';
update public.flashcards          set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch5\_%';
update public.formulas            set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch5\_%';
update public.user_topic_progress set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch5\_%';
update public.theory_content      set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch5\_%';
delete from public.topics where id like 'tmp\_ch5\_%';

commit;

-- Verification (shown as the result)
select coalesce(p."order", t."order") as topic_no, coalesce(p.title, t.title) as topic, t.id, t.title as subtopic,
       (select count(*) from public.questions  q where q.topic_id = t.id) as questions,
       (select count(*) from public.flashcards f where f.topic_id = t.id) as flashcards,
       (select count(*) from public.formulas   f where f.topic_id = t.id) as formulas,
       (select coalesce(jsonb_array_length(c.concepts), 0) from public.theory_content c where c.topic_id = t.id) as concept_blocks
from public.topics t left join public.topics p on p.id = t.parent_topic_id
where t.chapter_id = 'ch5'
order by coalesce(p."order", t."order"), t.parent_topic_id nulls first, t."order";
