-- =====================================================================
-- CH9 restructure: Chapter -> Topic (parent) -> Subtopic
-- Generated by tools/gen_chapter_migration.mjs from supabase/content/ch9/tree.json
-- on 20260925. Same mechanics as the Chapter 1 migration:
--   * parent topics ch9_p1, ch9_p2, ch9_p3, ch9_p4, ch9_p5, ch9_p6, ch9_p7
--   * every existing ch9 topic re-pointed via tmp_ ids (old/new ids overlap)
--   * questions, flashcards, formulas, theory, progress and attempts follow
--   * dropped topics: none
-- Runs as one transaction; backups go to schema "backup".
-- =====================================================================

begin;

create schema if not exists backup;
create table backup.ch9_topics_20260925         as select * from public.topics              where chapter_id = 'ch9';
create table backup.ch9_theory_content_20260925 as select * from public.theory_content      where topic_id like 'ch9\_%';
create table backup.ch9_questions_20260925      as select * from public.questions           where chapter_id = 'ch9';
create table backup.ch9_question_options_20260925 as select o.* from public.question_options o join public.questions q on q.id = o.question_id where q.chapter_id = 'ch9';
create table backup.ch9_flashcards_20260925     as select * from public.flashcards          where chapter_id = 'ch9';
create table backup.ch9_flashcard_reviews_20260925 as select r.* from public.flashcard_reviews r join public.flashcards f on f.id = r.card_id where f.chapter_id = 'ch9';
create table backup.ch9_formulas_20260925       as select * from public.formulas            where chapter_id = 'ch9';
create table backup.ch9_progress_20260925       as select * from public.user_topic_progress where topic_id like 'ch9\_%';
create table backup.ch9_attempts_20260925       as select * from public.question_attempts   where chapter_id = 'ch9';

alter table public.topics add column if not exists parent_topic_id text references public.topics(id);
create index if not exists topics_parent_topic_id_idx on public.topics(parent_topic_id);

-- Dropped topics and everything attached to them.
create temp table drop_topics(id text primary key) on commit drop;
-- (none)
delete from public.question_attempts where topic_id in (select id from drop_topics)
   or question_id in (select id from public.questions where topic_id in (select id from drop_topics));
delete from public.question_options  where question_id in (select id from public.questions where topic_id in (select id from drop_topics));
delete from public.questions         where topic_id in (select id from drop_topics);
delete from public.flashcard_reviews where card_id in (select id from public.flashcards where topic_id in (select id from drop_topics));
delete from public.flashcards        where topic_id in (select id from drop_topics);
delete from public.formulas          where topic_id in (select id from drop_topics);
delete from public.theory_content    where topic_id in (select id from drop_topics);
delete from public.user_topic_progress where topic_id in (select id from drop_topics);

-- Final tree.
create temp table new_topics(id text primary key, parent text, title text, ord int) on commit drop;
insert into new_topics values
  ('ch9_p1', null, 'Introduction to AI & Intelligent Agents', 1),
  ('ch9_t1', 'ch9_p1', 'AI Concepts, Perspectives, History, Applications & Foundations', 1),
  ('ch9_i11', 'ch9_p1', 'Intelligent Agents: Structure, Properties & PEAS', 2),
  ('ch9_i12', 'ch9_p1', 'Types of Agents: Simple Reflex, Model-Based, Goal-Based & Utility-Based', 3),
  ('ch9_i13', 'ch9_p1', 'Environment Types & Properties', 4),
  ('ch9_p2', null, 'Problem Solving & Searching Techniques', 2),
  ('ch9_t2', 'ch9_p2', 'Problem Formulation, State-Space Search & Well-Defined Problems', 1),
  ('ch9_i21', 'ch9_p2', 'Constraint Satisfaction Problems', 2),
  ('ch9_i22', 'ch9_p2', 'Uninformed Search: BFS, DFS, Depth-Limited, Iterative Deepening & Bidirectional', 3),
  ('ch9_i23', 'ch9_p2', 'Informed & Local Search: Greedy Best-First, A*, Hill Climbing & Simulated Annealing', 4),
  ('ch9_i24', 'ch9_p2', 'Game Playing: Adversarial Search, Minimax & Alpha-Beta Pruning', 5),
  ('ch9_p3', null, 'Knowledge Representation', 3),
  ('ch9_t3', 'ch9_p3', 'Knowledge Representation: Approaches, Issues, Semantic Nets & Frames', 1),
  ('ch9_i31', 'ch9_p3', 'Propositional Logic: Syntax, Semantics, Validity & Resolution', 2),
  ('ch9_i32', 'ch9_p3', 'First-Order Predicate Logic: Quantifiers, Inference, Unification & Resolution', 3),
  ('ch9_i33', 'ch9_p3', 'Bayes'' Rule, Bayesian Networks & Reasoning in Belief Networks', 4),
  ('ch9_p4', null, 'Expert Systems & Natural Language Processing', 4),
  ('ch9_t4', 'ch9_p4', 'Expert Systems: Architecture, Knowledge Acquisition & Development', 1),
  ('ch9_i41', 'ch9_p4', 'Natural Language Processing: Understanding, Generation, Steps & Challenges', 2),
  ('ch9_i42', 'ch9_p4', 'Machine Vision & Robotics', 3),
  ('ch9_p5', null, 'Machine Learning', 5),
  ('ch9_t5', 'ch9_p5', 'Learning Concepts: Supervised, Unsupervised & Reinforcement Learning', 1),
  ('ch9_i51', 'ch9_p5', 'Inductive Learning: Decision Trees, Entropy & Information Gain', 2),
  ('ch9_i52', 'ch9_p5', 'Statistical Learning: The Naive Bayes Model', 3),
  ('ch9_i53', 'ch9_p5', 'Fuzzy Learning & Fuzzy Inference Systems', 4),
  ('ch9_i54', 'ch9_p5', 'Genetic Algorithms: Encoding, Selection, Operators & Fitness', 5),
  ('ch9_p6', null, 'Neural Networks', 6),
  ('ch9_t6', 'ch9_p6', 'Biological vs Artificial Neurons, McCulloch–Pitts & the ANN Model', 1),
  ('ch9_i61', 'ch9_p6', 'Activation Functions & Neural Network Architectures', 2),
  ('ch9_i62', 'ch9_p6', 'The Perceptron: Learning Rate, Gradient Descent & the Delta Rule', 3),
  ('ch9_i63', 'ch9_p6', 'Hebbian Learning & the Adaline Network', 4),
  ('ch9_i64', 'ch9_p6', 'Multilayer Perceptron & Backpropagation', 5),
  ('ch9_i65', 'ch9_p6', 'Hopfield Neural Network', 6),
  ('ch9_p7', null, 'Quick Revision - Entire Chapter', 7),
  ('ch9_i71', 'ch9_p7', 'Algorithms, Formulas & Key Facts', 1);

-- Old id -> new id; seq orders theory blocks when old topics merge.
create temp table id_map(old_id text primary key, new_id text, seq int) on commit drop;
insert into id_map values
  ('ch9_i01', 'ch9_t1', 1),
  ('ch9_i02', 'ch9_i11', 1),
  ('ch9_i03', 'ch9_i12', 1),
  ('ch9_i04', 'ch9_t2', 1),
  ('ch9_i05', 'ch9_i23', 1),
  ('ch9_i06', 'ch9_i24', 1),
  ('ch9_i07', 'ch9_t3', 1),
  ('ch9_i08', 'ch9_i32', 1),
  ('ch9_i09', 'ch9_t4', 1),
  ('ch9_i10', 'ch9_i41', 1),
  ('ch9_i11', 'ch9_i42', 1),
  ('ch9_i12', 'ch9_t5', 1),
  ('ch9_i13', 'ch9_i52', 1),
  ('ch9_i14', 'ch9_t6', 1),
  ('ch9_i15', 'ch9_i62', 1);

do $$
declare missing text;
begin
  select string_agg(id, ', ') into missing
  from public.topics
  where chapter_id = 'ch9'
    and id not in (select old_id from id_map)
    and id not in (select id from drop_topics);
  if missing is not null then
    raise exception 'Unmapped ch9 topics: %', missing;
  end if;
end $$;

-- Stage through temporary topics.
insert into public.topics (id, chapter_id, title, description, icon, "order")
select distinct 'tmp_' || new_id, 'ch9', 'tmp', 'tmp', null, 0 from id_map;

update public.questions           x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;
update public.question_attempts   x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;
update public.flashcards          x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;
update public.formulas            x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;

create temp table progress_stage on commit drop as
select p.user_id, 'tmp_' || m.new_id as topic_id,
       bool_or(p.completed) as completed, max(p.completion_pct) as completion_pct, max(p.last_studied_at) as last_studied_at
from public.user_topic_progress p join id_map m on m.old_id = p.topic_id
group by p.user_id, m.new_id;
delete from public.user_topic_progress where topic_id in (select old_id from id_map);
insert into public.user_topic_progress (user_id, topic_id, completed, completion_pct, last_studied_at)
select user_id, topic_id, completed, completion_pct, last_studied_at from progress_stage;

create temp table theory_stage on commit drop as
select 'tmp_' || m.new_id as topic_id,
       coalesce(jsonb_agg(e.b order by m.seq, e.n) filter (where e.kind = 'concepts'), '[]'::jsonb) as concepts,
       coalesce(jsonb_agg(e.b order by m.seq, e.n) filter (where e.kind = 'formulas'), '[]'::jsonb) as formulas,
       coalesce(jsonb_agg(e.b order by m.seq, e.n) filter (where e.kind = 'notes'),    '[]'::jsonb) as notes
from public.theory_content t
join id_map m on m.old_id = t.topic_id
cross join lateral (
  select 'concepts' as kind, x.b, x.n from jsonb_array_elements(coalesce(t.concepts, '[]')) with ordinality x(b, n)
  union all
  select 'formulas', x.b, x.n from jsonb_array_elements(coalesce(t.formulas, '[]')) with ordinality x(b, n)
  union all
  select 'notes',    x.b, x.n from jsonb_array_elements(coalesce(t.notes, '[]'))    with ordinality x(b, n)
) e
group by m.new_id;
delete from public.theory_content where topic_id in (select old_id from id_map);
insert into public.theory_content (topic_id, concepts, formulas, notes)
select topic_id, concepts, formulas, notes from theory_stage;

-- Replace the old ch9 topics with the tree (parents first for the FK).
delete from public.topics where chapter_id = 'ch9' and id not like 'tmp\_%';
insert into public.topics (id, chapter_id, title, description, icon, "order", parent_topic_id)
select id, 'ch9', title, title, null, ord, parent from new_topics where parent is null;
insert into public.topics (id, chapter_id, title, description, icon, "order", parent_topic_id)
select id, 'ch9', title, title, null, ord, parent from new_topics where parent is not null;

update public.questions           set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch9\_%';
update public.question_attempts   set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch9\_%';
update public.flashcards          set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch9\_%';
update public.formulas            set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch9\_%';
update public.user_topic_progress set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch9\_%';
update public.theory_content      set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch9\_%';
delete from public.topics where id like 'tmp\_ch9\_%';

commit;

-- Verification (shown as the result)
select coalesce(p."order", t."order") as topic_no, coalesce(p.title, t.title) as topic, t.id, t.title as subtopic,
       (select count(*) from public.questions  q where q.topic_id = t.id) as questions,
       (select count(*) from public.flashcards f where f.topic_id = t.id) as flashcards,
       (select count(*) from public.formulas   f where f.topic_id = t.id) as formulas,
       (select coalesce(jsonb_array_length(c.concepts), 0) from public.theory_content c where c.topic_id = t.id) as concept_blocks
from public.topics t left join public.topics p on p.id = t.parent_topic_id
where t.chapter_id = 'ch9'
order by coalesce(p."order", t."order"), t.parent_topic_id nulls first, t."order";
