-- =====================================================================
-- CH6 restructure: Chapter -> Topic (parent) -> Subtopic
-- Generated by tools/gen_chapter_migration.mjs from supabase/content/ch6/tree.json
-- on 20260925. Same mechanics as the Chapter 1 migration:
--   * parent topics ch6_p1, ch6_p2, ch6_p3, ch6_p4, ch6_p5, ch6_p6, ch6_p7
--   * every existing ch6 topic re-pointed via tmp_ ids (old/new ids overlap)
--   * questions, flashcards, formulas, theory, progress and attempts follow
--   * dropped topics: none
-- Runs as one transaction; backups go to schema "backup".
-- =====================================================================

begin;

create schema if not exists backup;
create table backup.ch6_topics_20260925         as select * from public.topics              where chapter_id = 'ch6';
create table backup.ch6_theory_content_20260925 as select * from public.theory_content      where topic_id like 'ch6\_%';
create table backup.ch6_questions_20260925      as select * from public.questions           where chapter_id = 'ch6';
create table backup.ch6_question_options_20260925 as select o.* from public.question_options o join public.questions q on q.id = o.question_id where q.chapter_id = 'ch6';
create table backup.ch6_flashcards_20260925     as select * from public.flashcards          where chapter_id = 'ch6';
create table backup.ch6_flashcard_reviews_20260925 as select r.* from public.flashcard_reviews r join public.flashcards f on f.id = r.card_id where f.chapter_id = 'ch6';
create table backup.ch6_formulas_20260925       as select * from public.formulas            where chapter_id = 'ch6';
create table backup.ch6_progress_20260925       as select * from public.user_topic_progress where topic_id like 'ch6\_%';
create table backup.ch6_attempts_20260925       as select * from public.question_attempts   where chapter_id = 'ch6';

alter table public.topics add column if not exists parent_topic_id text references public.topics(id);
create index if not exists topics_parent_topic_id_idx on public.topics(parent_topic_id);

-- Dropped topics and everything attached to them.
create temp table drop_topics(id text primary key) on commit drop;
-- (none)
delete from public.question_attempts where topic_id in (select id from drop_topics)
   or question_id in (select id from public.questions where topic_id in (select id from drop_topics));
delete from public.question_options  where question_id in (select id from public.questions where topic_id in (select id from drop_topics));
delete from public.questions         where topic_id in (select id from drop_topics);
delete from public.flashcard_reviews where card_id in (select id from public.flashcards where topic_id in (select id from drop_topics));
delete from public.flashcards        where topic_id in (select id from drop_topics);
delete from public.formulas          where topic_id in (select id from drop_topics);
delete from public.theory_content    where topic_id in (select id from drop_topics);
delete from public.user_topic_progress where topic_id in (select id from drop_topics);

-- Final tree.
create temp table new_topics(id text primary key, parent text, title text, ord int) on commit drop;
insert into new_topics values
  ('ch6_p1', null, 'Finite Automata & Regular Languages', 1),
  ('ch6_t1', 'ch6_p1', 'Finite Automata: DFA, NFA & Their Equivalence', 1),
  ('ch6_i11', 'ch6_p1', 'Minimization of Finite State Machines', 2),
  ('ch6_i12', 'ch6_p1', 'Regular Expressions & Equivalence with Finite Automata', 3),
  ('ch6_i13', 'ch6_p1', 'Pumping Lemma for Regular Languages', 4),
  ('ch6_p2', null, 'Context-Free Languages', 2),
  ('ch6_t2', 'ch6_p2', 'Context-Free Grammars, Derivations & Parse Trees', 1),
  ('ch6_i21', 'ch6_p2', 'Ambiguity & Normal Forms: CNF, GNF & BNF', 2),
  ('ch6_i22', 'ch6_p2', 'Pushdown Automata & CFG–PDA Equivalence', 3),
  ('ch6_i23', 'ch6_p2', 'Pumping Lemma & Properties of Context-Free Languages', 4),
  ('ch6_p3', null, 'Turing Machines', 3),
  ('ch6_t3', 'ch6_p3', 'Turing Machine: Model, Notation & String Acceptance', 1),
  ('ch6_i31', 'ch6_p3', 'TM as Language Recognizer, Computing Function & Enumerator', 2),
  ('ch6_i32', 'ch6_p3', 'TM Variants: Multi-track, Multi-tape, Non-deterministic & Universal', 3),
  ('ch6_i33', 'ch6_p3', 'Church–Turing Thesis, Complexity, Intractability & Reducibility', 4),
  ('ch6_p4', null, 'Introduction to Computer Graphics', 4),
  ('ch6_t4', 'ch6_p4', 'Overview of Computer Graphics & Software Standards', 1),
  ('ch6_i41', 'ch6_p4', 'Display Technology: Raster-Scan & Vector Displays', 2),
  ('ch6_i42', 'ch6_p4', 'Display Processors, Input & Output Devices', 3),
  ('ch6_p5', null, 'Two-Dimensional Transformations', 5),
  ('ch6_t5', 'ch6_p5', '2D Translation, Rotation & Scaling', 1),
  ('ch6_i51', 'ch6_p5', '2D Reflection, Shear & Composite Transformations', 2),
  ('ch6_i52', 'ch6_p5', '2D Viewing Pipeline & Window-to-Viewport Mapping', 3),
  ('ch6_i53', 'ch6_p5', 'Line Clipping: Cohen–Sutherland & Liang–Barsky', 4),
  ('ch6_p6', null, 'Three-Dimensional Transformations', 6),
  ('ch6_t6', 'ch6_p6', '3D Translation, Rotation & Scaling', 1),
  ('ch6_i61', 'ch6_p6', '3D Reflection, Shear & Composite Transformations', 2),
  ('ch6_i62', 'ch6_p6', '3D Viewing Pipeline', 3),
  ('ch6_i63', 'ch6_p6', 'Projections: Parallel, Orthographic & Perspective', 4),
  ('ch6_p7', null, 'Quick Revision - Entire Chapter', 7),
  ('ch6_i71', 'ch6_p7', 'Key Facts, Matrices & Language Hierarchy', 1);

-- Old id -> new id; seq orders theory blocks when old topics merge.
create temp table id_map(old_id text primary key, new_id text, seq int) on commit drop;
insert into id_map values
  ('ch6_i01', 'ch6_t1', 1),
  ('ch6_i02', 'ch6_i12', 1),
  ('ch6_i03', 'ch6_t2', 1),
  ('ch6_i04', 'ch6_i22', 1),
  ('ch6_i05', 'ch6_t3', 1),
  ('ch6_i06', 'ch6_i33', 1),
  ('ch6_i07', 'ch6_i41', 1),
  ('ch6_i08', 'ch6_t5', 1),
  ('ch6_i09', 'ch6_i52', 1),
  ('ch6_i10', 'ch6_t6', 1),
  ('ch6_i11', 'ch6_i63', 1);

do $$
declare missing text;
begin
  select string_agg(id, ', ') into missing
  from public.topics
  where chapter_id = 'ch6'
    and id not in (select old_id from id_map)
    and id not in (select id from drop_topics);
  if missing is not null then
    raise exception 'Unmapped ch6 topics: %', missing;
  end if;
end $$;

-- Stage through temporary topics.
insert into public.topics (id, chapter_id, title, description, icon, "order")
select distinct 'tmp_' || new_id, 'ch6', 'tmp', 'tmp', null, 0 from id_map;

update public.questions           x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;
update public.question_attempts   x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;
update public.flashcards          x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;
update public.formulas            x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;

create temp table progress_stage on commit drop as
select p.user_id, 'tmp_' || m.new_id as topic_id,
       bool_or(p.completed) as completed, max(p.completion_pct) as completion_pct, max(p.last_studied_at) as last_studied_at
from public.user_topic_progress p join id_map m on m.old_id = p.topic_id
group by p.user_id, m.new_id;
delete from public.user_topic_progress where topic_id in (select old_id from id_map);
insert into public.user_topic_progress (user_id, topic_id, completed, completion_pct, last_studied_at)
select user_id, topic_id, completed, completion_pct, last_studied_at from progress_stage;

create temp table theory_stage on commit drop as
select 'tmp_' || m.new_id as topic_id,
       coalesce(jsonb_agg(e.b order by m.seq, e.n) filter (where e.kind = 'concepts'), '[]'::jsonb) as concepts,
       coalesce(jsonb_agg(e.b order by m.seq, e.n) filter (where e.kind = 'formulas'), '[]'::jsonb) as formulas,
       coalesce(jsonb_agg(e.b order by m.seq, e.n) filter (where e.kind = 'notes'),    '[]'::jsonb) as notes
from public.theory_content t
join id_map m on m.old_id = t.topic_id
cross join lateral (
  select 'concepts' as kind, x.b, x.n from jsonb_array_elements(coalesce(t.concepts, '[]')) with ordinality x(b, n)
  union all
  select 'formulas', x.b, x.n from jsonb_array_elements(coalesce(t.formulas, '[]')) with ordinality x(b, n)
  union all
  select 'notes',    x.b, x.n from jsonb_array_elements(coalesce(t.notes, '[]'))    with ordinality x(b, n)
) e
group by m.new_id;
delete from public.theory_content where topic_id in (select old_id from id_map);
insert into public.theory_content (topic_id, concepts, formulas, notes)
select topic_id, concepts, formulas, notes from theory_stage;

-- Replace the old ch6 topics with the tree (parents first for the FK).
delete from public.topics where chapter_id = 'ch6' and id not like 'tmp\_%';
insert into public.topics (id, chapter_id, title, description, icon, "order", parent_topic_id)
select id, 'ch6', title, title, null, ord, parent from new_topics where parent is null;
insert into public.topics (id, chapter_id, title, description, icon, "order", parent_topic_id)
select id, 'ch6', title, title, null, ord, parent from new_topics where parent is not null;

update public.questions           set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch6\_%';
update public.question_attempts   set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch6\_%';
update public.flashcards          set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch6\_%';
update public.formulas            set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch6\_%';
update public.user_topic_progress set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch6\_%';
update public.theory_content      set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch6\_%';
delete from public.topics where id like 'tmp\_ch6\_%';

commit;

-- Verification (shown as the result)
select coalesce(p."order", t."order") as topic_no, coalesce(p.title, t.title) as topic, t.id, t.title as subtopic,
       (select count(*) from public.questions  q where q.topic_id = t.id) as questions,
       (select count(*) from public.flashcards f where f.topic_id = t.id) as flashcards,
       (select count(*) from public.formulas   f where f.topic_id = t.id) as formulas,
       (select coalesce(jsonb_array_length(c.concepts), 0) from public.theory_content c where c.topic_id = t.id) as concept_blocks
from public.topics t left join public.topics p on p.id = t.parent_topic_id
where t.chapter_id = 'ch6'
order by coalesce(p."order", t."order"), t.parent_topic_id nulls first, t."order";
