-- =====================================================================
-- CH2 restructure: Chapter -> Topic (parent) -> Subtopic
-- Generated by tools/gen_chapter_migration.mjs from supabase/content/ch2/tree.json
-- on 20260925. Same mechanics as the Chapter 1 migration:
--   * parent topics ch2_p1, ch2_p2, ch2_p3, ch2_p4, ch2_p5, ch2_p6, ch2_p7
--   * every existing ch2 topic re-pointed via tmp_ ids (old/new ids overlap)
--   * questions, flashcards, formulas, theory, progress and attempts follow
--   * dropped topics: none
-- Runs as one transaction; backups go to schema "backup".
-- =====================================================================

begin;

create schema if not exists backup;
create table backup.ch2_topics_20260925         as select * from public.topics              where chapter_id = 'ch2';
create table backup.ch2_theory_content_20260925 as select * from public.theory_content      where topic_id like 'ch2\_%';
create table backup.ch2_questions_20260925      as select * from public.questions           where chapter_id = 'ch2';
create table backup.ch2_question_options_20260925 as select o.* from public.question_options o join public.questions q on q.id = o.question_id where q.chapter_id = 'ch2';
create table backup.ch2_flashcards_20260925     as select * from public.flashcards          where chapter_id = 'ch2';
create table backup.ch2_flashcard_reviews_20260925 as select r.* from public.flashcard_reviews r join public.flashcards f on f.id = r.card_id where f.chapter_id = 'ch2';
create table backup.ch2_formulas_20260925       as select * from public.formulas            where chapter_id = 'ch2';
create table backup.ch2_progress_20260925       as select * from public.user_topic_progress where topic_id like 'ch2\_%';
create table backup.ch2_attempts_20260925       as select * from public.question_attempts   where chapter_id = 'ch2';

alter table public.topics add column if not exists parent_topic_id text references public.topics(id);
create index if not exists topics_parent_topic_id_idx on public.topics(parent_topic_id);

-- Dropped topics and everything attached to them.
create temp table drop_topics(id text primary key) on commit drop;
-- (none)
delete from public.question_attempts where topic_id in (select id from drop_topics)
   or question_id in (select id from public.questions where topic_id in (select id from drop_topics));
delete from public.question_options  where question_id in (select id from public.questions where topic_id in (select id from drop_topics));
delete from public.questions         where topic_id in (select id from drop_topics);
delete from public.flashcard_reviews where card_id in (select id from public.flashcards where topic_id in (select id from drop_topics));
delete from public.flashcards        where topic_id in (select id from drop_topics);
delete from public.formulas          where topic_id in (select id from drop_topics);
delete from public.theory_content    where topic_id in (select id from drop_topics);
delete from public.user_topic_progress where topic_id in (select id from drop_topics);

-- Final tree.
create temp table new_topics(id text primary key, parent text, title text, ord int) on commit drop;
insert into new_topics values
  ('ch2_p1', null, 'Digital Logic', 1),
  ('ch2_t1', 'ch2_p1', 'Number Systems & Logic Levels', 1),
  ('ch2_i11', 'ch2_p1', 'Logic Gates & Truth Tables', 2),
  ('ch2_i12', 'ch2_p1', 'Boolean Algebra & De Morgan''s Theorems', 3),
  ('ch2_i13', 'ch2_p1', 'SOP & POS Forms', 4),
  ('ch2_i14', 'ch2_p1', 'Karnaugh Maps', 5),
  ('ch2_p2', null, 'Combinational & Arithmetic Circuits', 2),
  ('ch2_t2', 'ch2_p2', 'Combinational Circuits', 1),
  ('ch2_i21', 'ch2_p2', 'Multiplexers & Demultiplexers', 2),
  ('ch2_i22', 'ch2_p2', 'Decoders & Encoders', 3),
  ('ch2_i23', 'ch2_p2', 'Binary Adders & Subtractors', 4),
  ('ch2_i24', 'ch2_p2', 'Signed Numbers & 2''s Complement Arithmetic', 5),
  ('ch2_p3', null, 'Sequential Logic Circuits', 3),
  ('ch2_t3', 'ch2_p3', 'Flip-Flops & Latches', 1),
  ('ch2_i31', 'ch2_p3', 'Edge-Triggered & Master-Slave Flip-Flops', 2),
  ('ch2_i32', 'ch2_p3', 'Registers & Shift Register Applications', 3),
  ('ch2_i33', 'ch2_p3', 'Asynchronous & Synchronous Counters', 4),
  ('ch2_p4', null, 'Microprocessor', 4),
  ('ch2_t4', 'ch2_p4', 'Microprocessor Basics & Architecture', 1),
  ('ch2_i41', 'ch2_p4', 'Intel 8085 Architecture', 2),
  ('ch2_i42', 'ch2_p4', 'Intel 8086 Architecture', 3),
  ('ch2_i43', 'ch2_p4', 'Segment:Offset & Physical Address Calculation', 4),
  ('ch2_i44', 'ch2_p4', 'Addressing Modes (8085 & 8086)', 5),
  ('ch2_i45', 'ch2_p4', 'Instruction Set & Assembly Language Programming', 6),
  ('ch2_p5', null, 'Microprocessor System', 5),
  ('ch2_t5', 'ch2_p5', 'Memory Classification, Hierarchy & Interfacing', 1),
  ('ch2_i51', 'ch2_p5', 'Parallel Interface & the 8255 PPI', 2),
  ('ch2_i52', 'ch2_p5', 'Serial Interface & Communication Standards', 3),
  ('ch2_i53', 'ch2_p5', 'Direct Memory Access & DMA Controllers', 4),
  ('ch2_p6', null, 'Interrupt Operations', 6),
  ('ch2_t6', 'ch2_p6', 'Interrupts & Interrupt Service Routines', 1),
  ('ch2_i61', 'ch2_p6', 'Interrupt Processing, Vector Table & the 8259 PIC', 2),
  ('ch2_p7', null, 'Quick Revision - Entire Chapter', 7),
  ('ch2_i71', 'ch2_p7', 'Key Facts & Formulas', 1);

-- Old id -> new id; seq orders theory blocks when old topics merge.
create temp table id_map(old_id text primary key, new_id text, seq int) on commit drop;
insert into id_map values
  ('ch2_t1', 'ch2_t1', 1),
  ('ch2_t3', 'ch2_i11', 1),
  ('ch2_t2', 'ch2_i12', 1),
  ('ch2_i13', 'ch2_i13', 1),
  ('ch2_t4', 'ch2_i14', 1),
  ('ch2_t5', 'ch2_t2', 1),
  ('ch2_i14', 'ch2_i21', 1),
  ('ch2_i15', 'ch2_i22', 1),
  ('ch2_i16', 'ch2_i23', 1),
  ('ch2_i17', 'ch2_i24', 1),
  ('ch2_t6', 'ch2_t3', 1),
  ('ch2_t7', 'ch2_i32', 1),
  ('ch2_i18', 'ch2_t4', 1),
  ('ch2_t8', 'ch2_i42', 1),
  ('ch2_t9', 'ch2_i43', 1),
  ('ch2_t10', 'ch2_i44', 1),
  ('ch2_t11', 'ch2_i45', 1),
  ('ch2_t12', 'ch2_t5', 1),
  ('ch2_i19', 'ch2_i51', 1),
  ('ch2_i20', 'ch2_i52', 1),
  ('ch2_i21', 'ch2_i53', 1),
  ('ch2_i22', 'ch2_t6', 1),
  ('ch2_i23', 'ch2_i61', 1);

do $$
declare missing text;
begin
  select string_agg(id, ', ') into missing
  from public.topics
  where chapter_id = 'ch2'
    and id not in (select old_id from id_map)
    and id not in (select id from drop_topics);
  if missing is not null then
    raise exception 'Unmapped ch2 topics: %', missing;
  end if;
end $$;

-- Stage through temporary topics.
insert into public.topics (id, chapter_id, title, description, icon, "order")
select distinct 'tmp_' || new_id, 'ch2', 'tmp', 'tmp', null, 0 from id_map;

update public.questions           x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;
update public.question_attempts   x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;
update public.flashcards          x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;
update public.formulas            x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;

create temp table progress_stage on commit drop as
select p.user_id, 'tmp_' || m.new_id as topic_id,
       bool_or(p.completed) as completed, max(p.completion_pct) as completion_pct, max(p.last_studied_at) as last_studied_at
from public.user_topic_progress p join id_map m on m.old_id = p.topic_id
group by p.user_id, m.new_id;
delete from public.user_topic_progress where topic_id in (select old_id from id_map);
insert into public.user_topic_progress (user_id, topic_id, completed, completion_pct, last_studied_at)
select user_id, topic_id, completed, completion_pct, last_studied_at from progress_stage;

create temp table theory_stage on commit drop as
select 'tmp_' || m.new_id as topic_id,
       coalesce(jsonb_agg(e.b order by m.seq, e.n) filter (where e.kind = 'concepts'), '[]'::jsonb) as concepts,
       coalesce(jsonb_agg(e.b order by m.seq, e.n) filter (where e.kind = 'formulas'), '[]'::jsonb) as formulas,
       coalesce(jsonb_agg(e.b order by m.seq, e.n) filter (where e.kind = 'notes'),    '[]'::jsonb) as notes
from public.theory_content t
join id_map m on m.old_id = t.topic_id
cross join lateral (
  select 'concepts' as kind, x.b, x.n from jsonb_array_elements(coalesce(t.concepts, '[]')) with ordinality x(b, n)
  union all
  select 'formulas', x.b, x.n from jsonb_array_elements(coalesce(t.formulas, '[]')) with ordinality x(b, n)
  union all
  select 'notes',    x.b, x.n from jsonb_array_elements(coalesce(t.notes, '[]'))    with ordinality x(b, n)
) e
group by m.new_id;
delete from public.theory_content where topic_id in (select old_id from id_map);
insert into public.theory_content (topic_id, concepts, formulas, notes)
select topic_id, concepts, formulas, notes from theory_stage;

-- Replace the old ch2 topics with the tree (parents first for the FK).
delete from public.topics where chapter_id = 'ch2' and id not like 'tmp\_%';
insert into public.topics (id, chapter_id, title, description, icon, "order", parent_topic_id)
select id, 'ch2', title, title, null, ord, parent from new_topics where parent is null;
insert into public.topics (id, chapter_id, title, description, icon, "order", parent_topic_id)
select id, 'ch2', title, title, null, ord, parent from new_topics where parent is not null;

update public.questions           set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch2\_%';
update public.question_attempts   set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch2\_%';
update public.flashcards          set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch2\_%';
update public.formulas            set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch2\_%';
update public.user_topic_progress set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch2\_%';
update public.theory_content      set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch2\_%';
delete from public.topics where id like 'tmp\_ch2\_%';

commit;

-- Verification (shown as the result)
select coalesce(p."order", t."order") as topic_no, coalesce(p.title, t.title) as topic, t.id, t.title as subtopic,
       (select count(*) from public.questions  q where q.topic_id = t.id) as questions,
       (select count(*) from public.flashcards f where f.topic_id = t.id) as flashcards,
       (select count(*) from public.formulas   f where f.topic_id = t.id) as formulas,
       (select coalesce(jsonb_array_length(c.concepts), 0) from public.theory_content c where c.topic_id = t.id) as concept_blocks
from public.topics t left join public.topics p on p.id = t.parent_topic_id
where t.chapter_id = 'ch2'
order by coalesce(p."order", t."order"), t.parent_topic_id nulls first, t."order";
