-- =====================================================================
-- CH10 restructure: Chapter -> Topic (parent) -> Subtopic
-- Generated by tools/gen_chapter_migration.mjs from supabase/content/ch10/tree.json
-- on 20260925. Same mechanics as the Chapter 1 migration:
--   * parent topics ch10_p1, ch10_p2, ch10_p3, ch10_p4, ch10_p5, ch10_p6, ch10_p7
--   * every existing ch10 topic re-pointed via tmp_ ids (old/new ids overlap)
--   * questions, flashcards, formulas, theory, progress and attempts follow
--   * dropped topics: none
-- Runs as one transaction; backups go to schema "backup".
-- =====================================================================

begin;

-- New chapter row (a chapter with no earlier app content).
insert into public.chapters (id, title, description, emoji, icon, "order")
values ('ch10', 'Project Planning, Design & Implementation', 'Engineering drawing, engineering economics, project planning and scheduling, project management, professional practice and the Nepal Engineering Council.', '📐', null, 10)
on conflict (id) do update set title = excluded.title, description = excluded.description,
  emoji = excluded.emoji, icon = excluded.icon, "order" = excluded."order";

create schema if not exists backup;
create table backup.ch10_topics_20260925         as select * from public.topics              where chapter_id = 'ch10';
create table backup.ch10_theory_content_20260925 as select * from public.theory_content      where topic_id like 'ch10\_%';
create table backup.ch10_questions_20260925      as select * from public.questions           where chapter_id = 'ch10';
create table backup.ch10_question_options_20260925 as select o.* from public.question_options o join public.questions q on q.id = o.question_id where q.chapter_id = 'ch10';
create table backup.ch10_flashcards_20260925     as select * from public.flashcards          where chapter_id = 'ch10';
create table backup.ch10_flashcard_reviews_20260925 as select r.* from public.flashcard_reviews r join public.flashcards f on f.id = r.card_id where f.chapter_id = 'ch10';
create table backup.ch10_formulas_20260925       as select * from public.formulas            where chapter_id = 'ch10';
create table backup.ch10_progress_20260925       as select * from public.user_topic_progress where topic_id like 'ch10\_%';
create table backup.ch10_attempts_20260925       as select * from public.question_attempts   where chapter_id = 'ch10';

alter table public.topics add column if not exists parent_topic_id text references public.topics(id);
create index if not exists topics_parent_topic_id_idx on public.topics(parent_topic_id);

-- Dropped topics and everything attached to them.
create temp table drop_topics(id text primary key) on commit drop;
-- (none)
delete from public.question_attempts where topic_id in (select id from drop_topics)
   or question_id in (select id from public.questions where topic_id in (select id from drop_topics));
delete from public.question_options  where question_id in (select id from public.questions where topic_id in (select id from drop_topics));
delete from public.questions         where topic_id in (select id from drop_topics);
delete from public.flashcard_reviews where card_id in (select id from public.flashcards where topic_id in (select id from drop_topics));
delete from public.flashcards        where topic_id in (select id from drop_topics);
delete from public.formulas          where topic_id in (select id from drop_topics);
delete from public.theory_content    where topic_id in (select id from drop_topics);
delete from public.user_topic_progress where topic_id in (select id from drop_topics);

-- Final tree.
create temp table new_topics(id text primary key, parent text, title text, ord int) on commit drop;
insert into new_topics values
  ('ch10_p1', null, 'Engineering Drawings & Concepts', 1),
  ('ch10_t1', 'ch10_p1', 'Drawing Sheets, Dimensioning, Scales & Line Diagrams', 1),
  ('ch10_i11', 'ch10_p1', 'Orthographic Projection: First- & Third-Angle Views', 2),
  ('ch10_i12', 'ch10_p1', 'Isometric Projection & Pictorial Views', 3),
  ('ch10_i13', 'ch10_p1', 'Sectional Drawings', 4),
  ('ch10_p2', null, 'Engineering Economics', 2),
  ('ch10_t2', 'ch10_p2', 'Project Cash Flow, Interest & Time Value of Money', 1),
  ('ch10_i21', 'ch10_p2', 'Discounted Payback, NPV, IRR & MARR', 2),
  ('ch10_i22', 'ch10_p2', 'Comparison of Alternatives', 3),
  ('ch10_i23', 'ch10_p2', 'Depreciation & the Taxation System in Nepal', 4),
  ('ch10_p3', null, 'Project Planning & Scheduling', 3),
  ('ch10_t3', 'ch10_p3', 'Project Classification, Life-Cycle Phases & the Planning Process', 1),
  ('ch10_i31', 'ch10_p3', 'Bar Charts & the Critical Path Method (CPM)', 2),
  ('ch10_i32', 'ch10_p3', 'PERT: Three-Time Estimates & Probability of Completion', 3),
  ('ch10_i33', 'ch10_p3', 'Resource Levelling & Resource Smoothing', 4),
  ('ch10_i34', 'ch10_p3', 'Project Monitoring, Evaluation & Control', 5),
  ('ch10_p4', null, 'Project Management', 4),
  ('ch10_t4', 'ch10_p4', 'Project Management Information Systems', 1),
  ('ch10_i41', 'ch10_p4', 'Project Risk Analysis & Management', 2),
  ('ch10_i42', 'ch10_p4', 'Project Financing', 3),
  ('ch10_i43', 'ch10_p4', 'Tender & the Tendering Process', 4),
  ('ch10_i44', 'ch10_p4', 'Contract Management', 5),
  ('ch10_p5', null, 'Engineering Professional Practice', 5),
  ('ch10_t5', 'ch10_p5', 'Engineering, Environment & Society', 1),
  ('ch10_i51', 'ch10_p5', 'Professional Ethics & Codes of Conduct', 2),
  ('ch10_i52', 'ch10_p5', 'Regulatory Environment & Contemporary Issues in Engineering', 3),
  ('ch10_i53', 'ch10_p5', 'Occupational Health & Safety', 4),
  ('ch10_i54', 'ch10_p5', 'Nepal Engineers'' Association (NEA): Roles & Responsibilities', 5),
  ('ch10_p6', null, 'Engineering Regulatory Body', 6),
  ('ch10_t6', 'ch10_p6', 'Nepal Engineering Council: Establishment, Objectives & Functions', 1),
  ('ch10_i61', 'ch10_p6', 'NEC Act & Regulations: Registration, Categories & Renewal', 2),
  ('ch10_i62', 'ch10_p6', 'Professional Conduct, Misconduct & Disciplinary Action under the NEC Act', 3),
  ('ch10_p7', null, 'Quick Revision - Entire Chapter', 7),
  ('ch10_i71', 'ch10_p7', 'Formulas, Rules & Key Facts', 1);

-- Old id -> new id; seq orders theory blocks when old topics merge.
create temp table id_map(old_id text primary key, new_id text, seq int) on commit drop;
-- (no existing topics to map)

do $$
declare missing text;
begin
  select string_agg(id, ', ') into missing
  from public.topics
  where chapter_id = 'ch10'
    and id not in (select old_id from id_map)
    and id not in (select id from drop_topics);
  if missing is not null then
    raise exception 'Unmapped ch10 topics: %', missing;
  end if;
end $$;

-- Stage through temporary topics.
insert into public.topics (id, chapter_id, title, description, icon, "order")
select distinct 'tmp_' || new_id, 'ch10', 'tmp', 'tmp', null, 0 from id_map;

update public.questions           x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;
update public.question_attempts   x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;
update public.flashcards          x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;
update public.formulas            x set topic_id = 'tmp_' || m.new_id from id_map m where x.topic_id = m.old_id;

create temp table progress_stage on commit drop as
select p.user_id, 'tmp_' || m.new_id as topic_id,
       bool_or(p.completed) as completed, max(p.completion_pct) as completion_pct, max(p.last_studied_at) as last_studied_at
from public.user_topic_progress p join id_map m on m.old_id = p.topic_id
group by p.user_id, m.new_id;
delete from public.user_topic_progress where topic_id in (select old_id from id_map);
insert into public.user_topic_progress (user_id, topic_id, completed, completion_pct, last_studied_at)
select user_id, topic_id, completed, completion_pct, last_studied_at from progress_stage;

create temp table theory_stage on commit drop as
select 'tmp_' || m.new_id as topic_id,
       coalesce(jsonb_agg(e.b order by m.seq, e.n) filter (where e.kind = 'concepts'), '[]'::jsonb) as concepts,
       coalesce(jsonb_agg(e.b order by m.seq, e.n) filter (where e.kind = 'formulas'), '[]'::jsonb) as formulas,
       coalesce(jsonb_agg(e.b order by m.seq, e.n) filter (where e.kind = 'notes'),    '[]'::jsonb) as notes
from public.theory_content t
join id_map m on m.old_id = t.topic_id
cross join lateral (
  select 'concepts' as kind, x.b, x.n from jsonb_array_elements(coalesce(t.concepts, '[]')) with ordinality x(b, n)
  union all
  select 'formulas', x.b, x.n from jsonb_array_elements(coalesce(t.formulas, '[]')) with ordinality x(b, n)
  union all
  select 'notes',    x.b, x.n from jsonb_array_elements(coalesce(t.notes, '[]'))    with ordinality x(b, n)
) e
group by m.new_id;
delete from public.theory_content where topic_id in (select old_id from id_map);
insert into public.theory_content (topic_id, concepts, formulas, notes)
select topic_id, concepts, formulas, notes from theory_stage;

-- Replace the old ch10 topics with the tree (parents first for the FK).
delete from public.topics where chapter_id = 'ch10' and id not like 'tmp\_%';
insert into public.topics (id, chapter_id, title, description, icon, "order", parent_topic_id)
select id, 'ch10', title, title, null, ord, parent from new_topics where parent is null;
insert into public.topics (id, chapter_id, title, description, icon, "order", parent_topic_id)
select id, 'ch10', title, title, null, ord, parent from new_topics where parent is not null;

update public.questions           set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch10\_%';
update public.question_attempts   set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch10\_%';
update public.flashcards          set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch10\_%';
update public.formulas            set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch10\_%';
update public.user_topic_progress set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch10\_%';
update public.theory_content      set topic_id = substr(topic_id, 5) where topic_id like 'tmp\_ch10\_%';
delete from public.topics where id like 'tmp\_ch10\_%';

commit;

-- Verification (shown as the result)
select coalesce(p."order", t."order") as topic_no, coalesce(p.title, t.title) as topic, t.id, t.title as subtopic,
       (select count(*) from public.questions  q where q.topic_id = t.id) as questions,
       (select count(*) from public.flashcards f where f.topic_id = t.id) as flashcards,
       (select count(*) from public.formulas   f where f.topic_id = t.id) as formulas,
       (select coalesce(jsonb_array_length(c.concepts), 0) from public.theory_content c where c.topic_id = t.id) as concept_blocks
from public.topics t left join public.topics p on p.id = t.parent_topic_id
where t.chapter_id = 'ch10'
order by coalesce(p."order", t."order"), t.parent_topic_id nulls first, t."order";
